import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fixture,status,type Message} from './private-http-fixture';
import {hash} from '../src/http';
import {RecordCollection as C} from '../src/storage/repository';
const {chromium}=createRequire(import.meta.url)(process.env.TOKTOK_PLAYWRIGHT_MODULE||'@playwright/test');
const out=process.env.TOKTOK_BROWSER_OUTPUT||'.local/notice-browser';mkdirSync(out,{recursive:true});
const wanted=process.env.TOKTOK_NOTICE_CASES?.split(',');
for(const width of [390,1440])test('notice hierarchy shared surfaces and interaction '+width,async t=>{
 const f=await fixture(t),h=await f.session(),token=h.Cookie.split('=')[1];
 await f.repo.transaction('control',async tx=>{const session=(await tx.get(C.sessions,await hash(token)))!,key='a:'+session.owner_id,account=(await tx.get(C.accounts,key))!;await tx.put(C.accounts,key,{...account,role:'admin'});});
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),ctx=await browser.newContext({viewport:{width,height:950}}),page=await ctx.newPage();page.setDefaultTimeout(10000);await page.addInitScript(()=>{(window as any).__name=(value:any)=>value;});
 const raw={width,checks:[] as string[],failures:[] as {name:string;error:string}[],shots:[] as string[],pageErrors:0,apiMutations:0,cleanup:false};
 page.on('pageerror',()=>raw.pageErrors++);let fixtureMode=false;page.on('request',r=>{if(fixtureMode&&new URL(r.url()).pathname.startsWith('/api/')&&r.method()!=='GET')raw.apiMutations++;});
 await ctx.addCookies([{name:'__Host-toktok_session',value:token,domain:'localhost',path:'/',secure:true,httpOnly:true,sameSite:'Lax'}]);
 t.after(async()=>{await browser.close();raw.cleanup=true;writeFileSync(out+'/'+width+'-raw.json',JSON.stringify(raw,null,2));});
 async function check(name:string,task:()=>Promise<void>){if(wanted&&!wanted.includes(name))return;try{await task();raw.checks.push(name);}catch(e){raw.failures.push({name,error:String((e as Error).message).slice(0,900)});console.log('NOTICE_CHECK_FAIL '+JSON.stringify(raw.failures.at(-1)));}}
 async function shot(name:string){await page.evaluate(()=>{scrollTo({top:0,behavior:'instant'});return document.fonts.ready;});await page.screenshot({path:out+'/'+width+'-'+name+'.png',fullPage:true,animations:'disabled'});raw.shots.push(name);}
 async function metrics(){return page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,details:[...document.querySelectorAll('details.notice-disclosure>summary')].filter(e=>e.getClientRects().length).map(e=>({height:e.getBoundingClientRect().height,font:parseFloat(getComputedStyle(e).fontSize),color:getComputedStyle(e).color})),essential:[...document.querySelectorAll('.notice-essential,.check-row')].filter(e=>e.getClientRects().length).map(e=>parseFloat(getComputedStyle(e).fontSize))}));}
 // The actual protected route is opened with a fictional local admin. Its adapter stays isolated.
 if(!wanted||wanted.some(name=>!name.startsWith('actual-'))){assert.equal((await page.goto(f.origin+'/admin/design/components')).status(),200);await page.locator('#notice-example-closed').waitFor();
 await page.evaluate(async()=>{
  const registry=await import('/shared/registry.js'),{createFixtureAdapter}=await import('/admin/design/_assets/admin-design/fixture-adapter.js');
  const w=window as any;w.reviewRegistry=registry;w.reviewFixtures=createFixtureAdapter().catalog();
  w.paintReview=(id:string,mode='DEMO')=>{for(const d of document.querySelectorAll('dialog'))d.remove();const fixture=structuredClone(w.reviewFixtures.screens.find((f:any)=>f.fixtureId===id));if(!fixture)throw Error('MISSING_FIXTURE '+id);for(const vm of fixture.args){if(vm?.Config)vm.Config.mode=mode;}
   document.body.innerHTML='<div id="app"></div>';document.querySelector('#app')!.innerHTML=registry.screenRegistry[fixture.screenId].render(...fixture.args);
   const feed=document.querySelector('#feed');if(feed){feed.querySelector('#empty')?.remove();for(const [i,text] of ['대화가 먼저 보이는지 확인하는 가상 메시지예요.','필요한 설명은 아래에서 펼쳐 읽어요. 긴 내용도 자연스럽게 줄이 바뀌어야 해요. '.repeat(6)].entries()){feed.append(registry.componentRegistry.message.render({sequence:i+1,cursor:'fictional:'+i,sender:{id:'fictional-'+i,nickname:i?'June':'Milo'},created_at:'2026-10-03T14:00:00Z',text},i?'june':'milo'));}}};
 });fixtureMode=true;}
 const surfaces=['intro','rooms-default','newroom-anonymous','notice-newroom-policy-open','newroom-persist','newroom-created-recent','newroom-lost','auth-login','auth-signup-email','claim-unchecked','account-default','settings-private','settings-budget','adminlogs-invitations','adminlogs-audit','public-connection-pending','public-connection-approved','public-connection-legacy','public-connection-notice-unavailable','private-empty','private-persisted','private-memory','public-history-gap','guide'];
 await check('final-captures',async()=>{for(const id of ['intro','rooms-default','newroom-member','newroom-persist','auth-login','public-history-gap','settings-budget']){await page.evaluate(id=>(window as any).paintReview(id),id);await shot(id+'-final');}});
 await check('surfaces',async()=>{const invalid=[];for(const id of surfaces){await page.evaluate(({id,mode})=>(window as any).paintReview(id,mode),{id,mode:width===1440?'HOSTED':'DEMO'});await page.evaluate(()=>document.fonts.ready);const m=await metrics();await shot(id);if(m.overflow||m.details.some(d=>d.height<44||d.font!==12)||m.essential.some(n=>n<14))invalid.push({id,...m});}assert.deepEqual(invalid,[]);});
 await check('zoom',async()=>{const invalid=[];for(const id of ['intro','newroom-persist','private-empty','auth-login','public-connection-pending','settings-budget']){await page.evaluate(id=>(window as any).paintReview(id),id);await page.setViewportSize({width:Math.floor(width/2),height:475});await shot(id+'-zoom200');const m=await metrics();if(m.overflow)invalid.push({id,overflow:await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getClientRects().length&&(e.getBoundingClientRect().right>innerWidth+1||e.getBoundingClientRect().left< -1)).slice(0,15).map(e=>({tag:e.tagName,cls:e.className,id:e.id,width:e.getBoundingClientRect().width}))) });await page.setViewportSize({width,height:950});}assert.deepEqual(invalid,[]);});
 await check('newroom-continuity',async()=>{
  await page.evaluate(async()=>{const w=window as any;w.paintReview('newroom-member');const {mountNewRoom}=await import('/shared/newroom-mount.js');const base=w.reviewFixtures.screens.find((f:any)=>f.fixtureId==='newroom-persist').args[0];w.noticeCalls=[];w.noticeMount=mountNewRoom(document.querySelector('#app'),{effects:{getCreationOptions:async()=>({Session:base.Session,Config:base.Config}),createContext:async()=>{w.noticeCalls.push('context');throw Error('FICTIONAL_UNAVAILABLE');}},navigate:()=>{}});await w.noticeMount.load();});
  const summary=page.locator('#newroom-retention>summary');await summary.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#newroom-retention').evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await page.locator('#ownerRisk').isChecked(),false);assert.equal(await page.locator('button[type=submit]').isDisabled(),true);
  await page.locator('#roomPurpose').fill('가상 이름');await page.locator('#roomPurpose').press('ArrowLeft');const caret=await page.locator('#roomPurpose').evaluate(e=>(e as HTMLInputElement).selectionStart);await page.locator('#roomPurpose').press('x');assert.equal(await page.locator('#newroom-retention').evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await page.locator('#roomPurpose').evaluate(e=>(e as HTMLInputElement).selectionStart),caret!+1);
  await page.locator('input[name=persist][value=on]').check();assert.equal(await page.locator('#newroom-retention').evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await page.locator('#roomRetention').getAttribute('aria-describedby'),'room-retention-help');
  await summary.focus();await page.keyboard.press('Space');assert.equal(await page.locator('#newroom-retention').evaluate(e=>(e as HTMLDetailsElement).open),false);await page.locator('#ownerRisk').check();assert.equal(await page.locator('button[type=submit]').isEnabled(),true);await page.locator('button[type=submit]').click();await page.getByText('FICTIONAL_UNAVAILABLE',{exact:false}).waitFor();assert.deepEqual(await page.evaluate(()=>(window as any).noticeCalls),['context']);await shot('newroom-error');await page.evaluate(()=>(window as any).noticeMount.dispose());
 });
 await check('dialogs',async()=>{const bad=[];for(const [id,state] of [['public-connection','unchecked'],['public-connection','notice-unavailable'],['public-connection','revoke-error'],['public-risk','unchecked'],['settings-review','default'],['settings-reload','default'],['invitation-created','one-time'],['agent-revoke','error'],['admin-bootstrap','unchecked']]){
  await page.evaluate(([id,state])=>{const w=window as any;w.paintReview('intro');const f=w.reviewFixtures.dialogs.find((f:any)=>f.dialogId===id&&f.state===state),d=w.reviewRegistry.dialogRegistry[id].render(...f.args);document.body.append(d);d.showModal();},[id,state]);await shot('dialog-'+id+'-'+state);const m=await metrics();if(m.overflow||m.details.some(d=>d.height<44||d.font!==12)||m.essential.some(n=>n<14))bad.push({id,state,...m});
  if(id==='public-connection'&&state==='unchecked'){const dialog=page.locator('dialog'),summary=dialog.locator('summary').first();await summary.focus();await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement?.getAttribute('data-x')),'close-dialog');await summary.focus();await page.keyboard.press('Space');assert.equal(await summary.evaluate(e=>(e.parentElement as HTMLDetailsElement).open),true);assert.equal(await dialog.locator('[data-x=confirm-public-connection]').isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await dialog.evaluate(e=>(e as HTMLDialogElement).open),false);}
 }assert.deepEqual(bad,[]);});
 await check('public-dialog-continuity',async()=>{
  await page.evaluate(async()=>{const w=window as any;w.paintReview('intro');const {mountPublicConnection}=await import('/shared/public-connection-mount.js'),p=w.reviewFixtures.screens.find((f:any)=>f.fixtureId==='public-connection-pending').args[0];w.connectionCalls=[];w.noticeMount=mountPublicConnection(document.querySelector('#app'),{slug:'fictional-room',requestId:p.connection.request_id,navigate:()=>{},effects:{getSession:async()=>p.Session,getConfig:async()=>p.Config,publicConnection:async(_slug:string,body:any)=>{w.connectionCalls.push(body.action);if(body.action==='preview')return {...p.connection,nonce:'fictional-nonce'};throw Object.assign(Error(),{code:'OPERATOR_ACK_REQUIRED'});}}});await w.noticeMount.load();});
  await page.locator('[data-x=review-public-connection]').click();await page.locator('#public-entry-dialog-details>summary').click();await page.locator('#public-connection-ack').check();await page.locator('dialog [data-x=confirm-public-connection]').click();await page.locator('dialog .field-error').waitFor();assert.equal(await page.locator('#public-entry-dialog-details').evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await page.locator('#public-connection-ack').isChecked(),false);assert.deepEqual(await page.evaluate(()=>(window as any).connectionCalls),['preview','approve']);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.waitForFunction(()=>document.activeElement?.getAttribute('data-x')==='review-public-connection');await shot('public-approval-error-return');await page.evaluate(()=>(window as any).noticeMount.dispose());
 });
 await check('auth-error-continuity',async()=>{
  await page.evaluate(async()=>{const w=window as any;w.paintReview('auth-login');const {mountAuth}=await import('/shared/auth-mount.js'),base=w.reviewFixtures.screens.find((f:any)=>f.fixtureId==='auth-login').args.at(-1);w.authCalls=[];w.noticeMount=mountAuth(document.querySelector('#app'),{navigate:()=>{},effects:{getConfig:async()=>base.Config,getSession:async()=>base.Session,startAuth:async()=>{w.authCalls.push('start');return {flow:'fictional-flow',nonce:'fictional-nonce',expires_at:new Date(Date.now()+60000).toISOString(),provider_configured:true};},sendEmail:async()=>{w.authCalls.push('send');throw Object.assign(Error(),{code:'FICTIONAL_MAIL_UNAVAILABLE'});}}});await w.noticeMount.load('login','/');});
  await page.locator('#email-processing>summary').click();await page.locator('input[name=email]').fill('fictional@example.test');await page.locator('#xAuthForm button').click();await page.locator('.field-error').waitFor();assert.equal(await page.locator('#email-processing').evaluate(e=>(e as HTMLDetailsElement).open),true);assert.deepEqual(await page.evaluate(()=>(window as any).authCalls),['start','send']);await page.locator('#xAuthForm button').click();await page.waitForFunction(()=>(window as any).authCalls.length===3);assert.equal(await page.locator('#email-processing').evaluate(e=>(e as HTMLDetailsElement).open),true);await shot('auth-send-error');await page.evaluate(()=>{(window as any).noticeMount.enter('signup','/');});assert.equal(await page.locator('#email-processing[open]').count(),0);await page.evaluate(()=>(window as any).noticeMount.dispose());
 });
 await check('review-delta-surfaces',async()=>{for(const id of ['public-history-gap','public-connection-pending','public-connection-approved']){await page.evaluate(id=>(window as any).paintReview(id),id);await shot(id+'-review-final');const m=await metrics();assert.equal(m.overflow,false);assert(m.essential.every(n=>n>=14));}});
 fixtureMode=false;
 await check('actual-public',async()=>{
  const metadataReply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/public/rooms/common-room'&&r.status()===200);await page.goto(f.origin+'/public/common-room');const snapshot={data:await (await metadataReply).json()};await page.waitForFunction(()=>document.querySelector('[data-role=public-retention]')?.textContent?.includes('2MiB'));assert.equal(await page.locator('[data-role=private-retention]').count(),0);assert.equal(await page.locator('#public-retention').count(),1);assert.equal(await page.locator('#public-notice').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),14);await page.locator('#public-retention>summary').click();assert.match(await page.locator('#public-retention').innerText(),new RegExp(String(snapshot.data.recent_buffer.max_messages)));await page.locator('[data-action=pause]').click();await shot('actual-public-chat');await page.locator('[data-tab=connect]').click();await page.locator('#public-agent-guide>summary').click();assert.match(await page.locator('#public-agent-guide').innerText(),/사람이 명시적으로 허용/);assert.equal(await page.locator('#public-agent-guide a').getAttribute('href'),'/public/common-room?format=md');await shot('actual-public-connect');await page.goto(f.origin+'/about');
 });
 await check('actual-qa',async()=>{
  if(!wanted||wanted.some(name=>name!=='actual-qa')){await page.goto('about:blank');await new Promise(resolve=>setTimeout(resolve,61000));}
  const denied=await fetch(f.origin+'/admin/design/components');assert([401,403].includes(denied.status));const deniedAsset=await fetch(f.origin+'/admin/design/_assets/admin-design/notice-fixtures.js');assert([401,403].includes(deniedAsset.status));fixtureMode=true;
  const failedAssets=[] as {path:string;status:number}[];const assetListener=(r:any)=>{const p=new URL(r.url()).pathname;if(r.status()>=400&&(p.startsWith('/admin/design')||p.startsWith('/shared/')||p.endsWith('.css')))failedAssets.push({path:p,status:r.status()});};page.on('response',assetListener);const galleryReply=await page.goto(f.origin+'/admin/design/dialogues');assert.equal(galleryReply.status(),200,'gallery HTML');try{await page.locator('#design-review button').first().waitFor();}catch{throw Error(JSON.stringify({url:new URL(page.url()).pathname,body:(await page.locator('body').innerText()).slice(0,200),failedAssets}));}assert((await page.locator('#design-review').innerText()).includes('public-connection'),'gallery bootstrap '+(await page.locator('#design-review').innerText()).slice(0,180));const trigger=page.getByRole('button',{name:'public-connection · unchecked',exact:true});await trigger.click();const shell=page.locator('.dialog-review-shell'),summary=shell.locator('#public-entry-dialog-details>summary');await summary.focus();await page.keyboard.press('Space');assert.equal(await shell.locator('#public-entry-dialog-details').evaluate(e=>(e as HTMLDetailsElement).open),true);await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement?.getAttribute('data-review')),'close');await page.keyboard.press('Shift+Tab');assert.equal(await summary.evaluate(e=>document.activeElement===e),true);await shot('qa-dialog-disclosure');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.dialog-review-shell'));await page.waitForFunction(()=>document.activeElement?.textContent==='public-connection · unchecked');
  await page.goto('about:blank');await new Promise(resolve=>setTimeout(resolve,61000));await page.goto(f.origin+'/admin/design/flows');await page.locator('.flow-node').first().waitFor();await page.waitForFunction(()=>{const nodes=[...document.querySelectorAll('.flow-node')].filter(e=>e.getAttribute('data-node')?.includes('notice-newroom-policy-open'));return nodes.length>0&&nodes.every(e=>e.querySelector('iframe')?.getAttribute('data-preview-ready')==='true');},{},{timeout:20000});
  const state=await page.evaluate(()=>[...document.querySelectorAll('.flow-node')].filter(e=>e.getAttribute('data-node')?.includes('notice-newroom-policy-open')).map(e=>{const f=e.querySelector('iframe')!,d=f.contentDocument!;return {open:(d.querySelector('#newroom-retention') as HTMLDetailsElement)?.open,styles:d.querySelectorAll('link[data-product-styles]').length,error:f.dataset.previewError??null};}));assert(state.length>0);assert(state.every(s=>s.open&&s.styles===1&&s.error===null));await shot('qa-notice-flow');fixtureMode=false;
 });
 await check('actual-private',async()=>{const owned=(await f.create(await f.grant(h))).owned,participant=await f.participate(owned);status(await f.call<Message>('notice local message',owned.base+'/messages','POST',{text:'공통 보관 안내를 확인하는 실제 로컬 가상 대화예요.',client_message_id:'notice-browser-'+width},participant.participant.participant_token),201,'write');
  await page.goto(owned.read_url);await page.locator('#feed .message').waitFor();assert.match(await page.locator('[data-role=private-retention]').innerText(),/최근 대화 보관/);assert.equal(await page.locator('#retention-summary').count(),0);await page.locator('#private-retention-chat>summary').click();await page.locator('[data-action=pause]').click();await page.locator('[data-action=pause]').click();assert.equal(await page.locator('#private-retention-chat').evaluate(e=>(e as HTMLDetailsElement).open),true);await page.locator('[data-tab=connect]').click();assert.match(await page.locator('[data-role=link-access-scope]').innerText(),/종단 간 암호화/);assert.equal(await page.locator('#private-notice details[data-notice-version]').count(),2);await page.locator('#shared-url').evaluate(e=>e.textContent='https://toktok.example/r/FICTIONAL/READ_LINK');await shot('actual-private-connect-redacted');await page.goto(f.origin+'/about');status(await f.call('notice local cleanup',owned.base,'DELETE',undefined,owned.owner_token),204,'cleanup');});
 assert.equal(raw.apiMutations,0,'fixture operations must never call live mutation APIs');assert.equal(raw.pageErrors,0,'browser runtime errors');assert.deepEqual(raw.failures,[],'see per-case evidence');console.log('NOTICE_BROWSER '+JSON.stringify({width,passed:raw.checks,shots:raw.shots.length,apiMutations:raw.apiMutations,pageErrors:raw.pageErrors}));
});
