import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const percentile=values=>{const s=[...values].sort((a,b)=>a-b);return {count:s.length,p50_ms:s.length?s[Math.floor(s.length*.5)]:null,p95_ms:s.length?s[Math.floor(s.length*.95)]:null,max_ms:s.at(-1)??null};};
function noSecrets(value){if(!value||typeof value!=='object')return;for(const [key,v] of Object.entries(value)){assert.ok(!/^(body|text|ip|token|lease_token|operator_grant|authorization)$/i.test(key));noSecrets(v);}}
const scenarios=[];
for(const name of ['A','B','C','D','E']){const r=JSON.parse(await readFile(`test/public-load.compare-${name}.json`,'utf8'));noSecrets(r);
 const duration=cases=>({empty_timeout:percentile(cases.filter(c=>c.kind==='read'&&c.status===200&&c.page_count===0).map(c=>c.duration_ms)),nonempty:percentile(cases.filter(c=>c.kind==='read'&&c.status===200&&c.page_count>0).map(c=>c.duration_ms))});
 const raw=r.rawCases.filter(c=>c.measurement_request),statuses={};for(const c of raw)if(c.status!==undefined)statuses[c.status]=(statuses[c.status]??0)+1;
 const backlog=r.rawCases.filter(c=>c.kind==='read'&&c.status===200).map(c=>{const [epoch,seq]=c.cursor.split(':');return Math.max(0,...r.accepted.filter(a=>a.epoch===epoch&&a.created_at_ms<=c.consumed_at_ms).map(a=>a.sequence-Number(seq)));});
 const appliedInWindow=r.deliveries.filter(d=>!d.recovery),byRole={};for(const role of ['participant','watcher'])byRole[role]=percentile(r.deliveries.filter(d=>d.client.startsWith(role+'-')).map(d=>d.lag_ms));
 assert.equal(raw.length,r.window.requests_started);assert.equal(r.counts.actually_applied,r.deliveries.length);
 assert.equal(r.counts.missing_deliveries,0);assert.equal(r.counts.gap_notices,0);assert.ok(Object.values(r.invariants).every(Boolean));
 scenarios.push({scenario:name,seed:r.seed,participants:r.participants,watchers:r.watchers,policy:r.policy,window_requests:r.window.requests_started,request_rate:r.window.requests_started/60,read_requests:raw.filter(c=>c.kind==='read').length,statuses,scheduled:r.window.scheduled_messages,accepted:r.window.accepted_server,pending_or_unaccepted:r.window.pending_or_unaccepted,applied_during_window:appliedInWindow.length,applied_after_window:r.deliveries.length-appliedInWindow.length,applied_total:r.deliveries.length,missing_after_observation:r.counts.missing_deliveries,gap_reset:r.counts.gap_notices,duration_window:duration(raw),duration_recovery:duration(r.rawCases.filter(c=>!c.measurement_request)),delivery_lag:percentile(r.deliveries.map(d=>d.lag_ms)),delivery_lag_during_window:percentile(appliedInWindow.map(d=>d.lag_ms)),delivery_lag_by_role:byRole,max_timestamp_estimated_backlog:Math.max(0,...backlog),has_more_responses:r.rawCases.filter(c=>c.has_more).length,recovery:r.recovery,app_message_bytes:r.diagnostics.buffer_bytes/r.diagnostics.message_count,read_json_bytes:raw.filter(c=>c.kind==='read'&&c.status===200).reduce((n,c)=>n+c.bytes,0),maxPageBytes:r.maxResponseBytes,cleanup_zero:r.invariants.cleanup_zero,unmeasured_heap:true});
}
await writeFile('test/public-load.comparison-summary.json',JSON.stringify({scenarios,price_inputs_exclude_recovery:true,backlog_estimate:'acknowledged accepted sequence at consumption timestamp minus returned cursor; not a new server counter'},null,2)+'\n');
console.log(JSON.stringify(scenarios.map(r=>({scenario:r.scenario,rps:r.request_rate,accepted:r.accepted,pending:r.pending_or_unaccepted,delivery_p95_ms:r.delivery_lag.p95_ms,backlog:r.max_timestamp_estimated_backlog,recovery_ms:r.recovery.duration_ms}))));
