import {it,expect} from 'vitest';
import {handlePublicBrowser,edgeIP} from '../src/public-browser';
import type {Env} from '../src/contracts';
const origin='https://toktok.example';
const make=(path:string,method='GET',data?:unknown,headers:Record<string,string>={})=>new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});
function fixture(){let grants=0,fetches=0;let result={status:201,data:{operator_grant:'test-grant',epoch:'test',expires_at:new Date(Date.now()+300000).toISOString(),notice_version:'toktok-risk-v1'},retry_after_ms:undefined as number|undefined};const env={PUBLIC_ORIGIN:origin,ASSETS:{fetch:async()=>new Response('<html>Common room</html>',{headers:{'Content-Type':'text/html'}})},IP_RATE_LIMIT:{limit:async()=>({success:true})},PUBLIC_ROOMS:{getByName:()=>({fetch:async()=>{fetches++;return Response.json({});},issueOperatorGrant:async()=>{grants++;return result;}})}} as unknown as Env;return {env,counts:()=>({grants,fetches}),setResult:(v:any)=>{result=v;}};}
const dep={trustedIP:()=> '192.0.2.1'};
const base='/api/public/rooms/common-room';
it('keeps HTML, Markdown and API errors separate and all GETs admission free',async()=>{const f=fixture();for(const req of [make('/public/common-room'),make('/public/common-room?format=md'),make('/public/common-room','GET',undefined,{Accept:'text/markdown'}),make('/api/public/rooms')]){const r=await handlePublicBrowser(req,f.env,dep);expect(r?.status).toBe(200);}expect(f.counts()).toEqual({grants:0,fetches:0});expect((await handlePublicBrowser(make('/public/missing'),f.env,dep))?.status).toBe(404);expect((await handlePublicBrowser(make(base+'/missing'),f.env,dep))?.headers.get('Content-Type')).toContain('application/json');});
it('requires exact Origin, cookie/nonce/room/time and explicit risk acknowledgement before RPC',async()=>{const f=fixture(),r=await handlePublicBrowser(make(base+'/ack-flow','POST',{}),f.env,dep);expect(r?.status).toBe(201);const flow=await r!.json() as {nonce:string};const cookie=r!.headers.get('Set-Cookie')!;expect(cookie).toContain('__Host-toktok-public-flow=');for(const bit of ['Secure','HttpOnly','SameSite=Strict','Path=/','Max-Age=300'])expect(cookie).toContain(bit);const body={nonce:flow.nonce,checked:true,risk_ack_version:'toktok-risk-v1'};for(const [patch,head,path] of [[{}, {Origin:''},base],[{}, {Origin:'https://evil.example'},base],[{nonce:'x'.repeat(43)}, {},base],[{checked:false},{},base],[{risk_ack_version:'wrong'},{},base],[{}, {},'/api/public/rooms/workshop']] as const){const denied=await handlePublicBrowser(make(path+'/operator-grants','POST',{...body,...patch},{Cookie:cookie,...head}),f.env,dep);expect(denied?.status).toBe(403);}for(const issued_at of [Date.now()-300001,Date.now()+60000]){const forged=encodeURIComponent(JSON.stringify({room:'common-room',nonce:flow.nonce,issued_at}));expect((await handlePublicBrowser(make(base+'/operator-grants','POST',body,{Cookie:'__Host-toktok-public-flow='+forged}),f.env,dep))?.status).toBe(403);}expect(f.counts().grants).toBe(0);const ok=await handlePublicBrowser(make(base+'/operator-grants','POST',body,{Cookie:cookie}),f.env,dep);expect(ok?.status).toBe(201);expect(await ok!.json()).toMatchObject({operator_grant:'test-grant'});expect(ok!.headers.get('Set-Cookie')).toContain('Max-Age=0');f.setResult({status:429,data:{error:{code:'RATE_LIMITED',message:'limited',retry_after_ms:2345}},retry_after_ms:2345});const limited=await handlePublicBrowser(make(base+'/operator-grants','POST',body,{Cookie:cookie}),f.env,dep);expect(limited?.status).toBe(429);expect(limited?.headers.get('Retry-After')).toBe('3');});
it('rejects spoofed IP provenance and normalizes only direct edge IP',()=>{for(const headers of ([{'CF-Connecting-IP':'192.0.2.1'},{'X-Forwarded-For':'192.0.2.1'},{'x-toktok-public-ip-hash':'a'.repeat(64)}] as Record<string,string>[]))expect(()=>edgeIP(make(base,'GET',undefined,headers))).toThrow();const direct=make(base,'GET',undefined,{'CF-Connecting-IP':'2001:db8:0:0::1'});Object.defineProperty(direct,'cf',{value:{colo:'FRA'}});expect(edgeIP(direct)).toBe('2001:db8::1');direct.headers.set('CF-Connecting-IPv6','2001:db8::99');expect(edgeIP(direct)).toBe('2001:db8::1');const sub=new Request(direct,{headers:{'CF-Connecting-IP':'192.0.2.1','CF-Worker':'other.example'}});Object.defineProperty(sub,'cf',{value:{colo:'FRA'}});expect(()=>edgeIP(sub)).toThrow();});
