import {env} from 'cloudflare:workers';
import {runInDurableObject,evictDurableObject} from 'cloudflare:test';
import {it,expect} from 'vitest';
import type {PrivateRoom,RecordFixture} from './selfhost-worker';
import {PrivateRoomCore} from '../src/private-core';
import {CloudflareRepository} from '../src/storage/cloudflare';
import {privateSnapshot} from './selfhost-private-fixture';
import {TEST_BUDGET} from './selfhost-budget';
interface Env{PRIVATE_ROOMS:DurableObjectNamespace<PrivateRoom>;RECORD_ROOMS:DurableObjectNamespace<RecordFixture>;}
it('CF private runtime keeps memory body out of SQLite and persists opted-in history across core restart',async()=>{
 for(const persist of [false,true]){const id=persist?'cf-persist':'cf-memory',stub=(env as unknown as Env).PRIVATE_ROOMS.getByName(id),{tokens,snapshot}=await privateSnapshot(id,persist);await stub.initialize(snapshot);
 const call=async(path:string,method='GET',data?:object,token=tokens.read)=>{const r=await stub.fetch(new Request('http://localhost:18794/api/v1/rooms/'+id+path,{method,headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined}));return new Response(r.status===204?null:await r.arrayBuffer(),r);};
 const joined=await call('/participants','POST',{nickname:'mock CF',client_request_id:'join',notice_version:snapshot.notice_version,visibility:'private',retention_mode:persist?'persisted':'memory'},tokens.invite);const joinedData=await joined.json() as {participant_token:string;error?:{code:string}};const schema=await runInDurableObject<PrivateRoom,{tables:string[]}>(stub,(_room,ctx)=>({tables:ctx.storage.sql.exec("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").toArray().map(r=>String(r.name))}));console.log(JSON.stringify({phase:'cf-private-join',persist,status:joined.status,error_code:joinedData.error?.code??null,tables:schema.tables}));expect(joined.status).toBe(201);const token=joinedData.participant_token;
 const sent=await call('/messages','POST',{text:'mock CF body',client_message_id:'one'},token);expect(sent.status).toBe(201);const message=await sent.json() as {cursor:string};
 const result=await runInDurableObject<PrivateRoom,{bodyRows:number;status:number;history:string;messages:number;epoch:string}>(stub,async(_room,ctx)=>{const rows=ctx.storage.sql.exec("SELECT COUNT(*) AS n FROM tok_records WHERE collection='private_messages' AND key LIKE 'm:%'").one();const restarted=new PrivateRoomCore({origin:'http://localhost:18794',repo:new CloudflareRepository(ctx.storage),budget:TEST_BUDGET});const response=await restarted.fetch(new Request('http://localhost:18794/api/v1/rooms/'+id+'/messages?after='+encodeURIComponent(message.cursor.split(':')[0]+':0'),{headers:{Authorization:'Bearer '+tokens.read}}));const page=await response.json() as {history_status:string;messages:unknown[];epoch:string};restarted.shutdown();return {bodyRows:Number(rows.n),status:response.status,history:page.history_status,messages:page.messages.length,epoch:page.epoch};});expect(result.status).toBe(200);expect(result.bodyRows).toBe(persist?1:0);expect(result.history).toBe(persist?'ok':'history_reset');expect(result.messages).toBe(persist?1:0);console.log(JSON.stringify({phase:'cf-private',persist,body_rows:result.bodyRows,history:result.history,message_count:result.messages}));
 }
});
it('CF metered targeted reserve and cleanup includes SQLite index row operations',async()=>{const stub=(env as unknown as Env).RECORD_ROOMS.getByName('meter');const measured=await stub.meterProbe();expect(measured.reserve.rowsWritten).toBeGreaterThan(0);expect(measured.cleanup.rowsWritten).toBeGreaterThan(0);console.log(JSON.stringify({phase:'record-sql-meter',...measured}));});

it('CF trusted host inspect binds id on fresh actor after restart',async()=>{
 const id='cf-host-inspect',stub=(env as unknown as Env).PRIVATE_ROOMS.getByName(id),{snapshot}=await privateSnapshot(id,false);await stub.initialize(snapshot);await evictDurableObject(stub);const view=await stub.inspect(id) as {id:string;status:string;initialized:boolean};expect(view).toMatchObject({id,status:'open',initialized:true});console.log(JSON.stringify({phase:'fresh-actor-inspect',initialized:view.initialized,status:view.status}));
});

it('CF cold alarm restores exact ID-only bootstrap and partial init never becomes success',async()=>{
 const id='cf-cold-alarm',stub=(env as unknown as Env).PRIVATE_ROOMS.getByName(id),{snapshot}=await privateSnapshot(id,false);await stub.initialize(snapshot);await evictDurableObject(stub);
 const cold=await runInDurableObject<PrivateRoom,{keys:string[];idMatches:boolean;bodyRows:number;initialized:boolean}>(stub,async(instance,ctx)=>{await instance.alarm();const metadata=await ctx.storage.list(),view=await instance.inspect() as {initialized:boolean};return {keys:[...metadata.keys()],idMatches:metadata.get('toktok_private_room_id')===id,bodyRows:Number(ctx.storage.sql.exec("SELECT COUNT(*) AS n FROM tok_records WHERE collection='private_messages'").one().n),initialized:view.initialized};});expect(cold).toEqual({keys:['toktok_private_room_id'],idMatches:true,bodyRows:0,initialized:true});
 const failedId='cf-partial-bootstrap',failed=(env as unknown as Env).PRIVATE_ROOMS.getByName(failedId),expired=await privateSnapshot(failedId,false,Date.now()-1000000);
 const partial=await runInDurableObject<PrivateRoom,{keys:string[];snapshotRows:number;initialized:boolean}>(failed,async(instance,ctx)=>{try{await instance.initialize(expired.snapshot);}catch{}let initialized=false;try{initialized=(await instance.inspect(failedId) as {initialized:boolean}).initialized;}catch{}return {keys:[...(await ctx.storage.list()).keys()],snapshotRows:Number(ctx.storage.sql.exec("SELECT COUNT(*) AS n FROM tok_records WHERE collection='private_rooms'").one().n),initialized};});expect(partial).toEqual({keys:['toktok_private_room_id'],snapshotRows:0,initialized:false});console.log(JSON.stringify({phase:'cold-alarm-bootstrap',kv_id_only:true,body_rows:cold.bodyRows,cold_initialized:cold.initialized,partial_snapshot_rows:partial.snapshotRows,partial_initialized:partial.initialized}));
});

it('CF bootstrap schema names diagnostic only',async()=>{const stub=(env as unknown as Env).PRIVATE_ROOMS.getByName('cf-bootstrap-schema-probe');const tables=await runInDurableObject<PrivateRoom,{name:string;type:string}[]>(stub,async(_room,ctx)=>{await ctx.storage.put('toktok_private_room_id','cf-bootstrap-schema-probe');return ctx.storage.sql.exec<{name:string;type:string}>("SELECT name,type FROM sqlite_master WHERE type IN ('table','view','trigger') AND name NOT LIKE 'sqlite_%' ORDER BY name").toArray();});console.log(JSON.stringify({phase:'bootstrap-schema-names',tables}));expect(tables.length).toBeGreaterThan(0);});

it('CF blank GET returns 404 without schema or metadata and preserves existing cold and schema conflicts',async()=>{
 const id='cf-unknown-room',stub=(env as unknown as Env).PRIVATE_ROOMS.getByName(id),request=(room:string,token?:string)=>new Request('http://localhost:18794/api/v1/rooms/'+room,{headers:token?{Authorization:'Bearer '+token}:{}});
 const missing=await stub.fetch(request(id)),error=await missing.json() as {error:{code:string}};console.log(JSON.stringify({phase:'unknown-private-get',status:missing.status,error_code:error.error.code}));expect(missing.status).toBe(404);expect(error.error.code).toBe('ROOM_NOT_FOUND');
 const blank=await runInDurableObject<PrivateRoom,{userTables:number;metadataKeys:number}>(stub,async(_room,ctx)=>({userTables:ctx.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").one().n,metadataKeys:(await ctx.storage.list()).size}));expect(blank).toEqual({userTables:0,metadataKeys:0});
 const existingId='cf-get-existing',existing=(env as unknown as Env).PRIVATE_ROOMS.getByName(existingId),{tokens,snapshot}=await privateSnapshot(existingId,false);await existing.initialize(snapshot);let page=await existing.fetch(request(existingId,tokens.read));expect(page.status).toBe(200);await page.arrayBuffer();await evictDurableObject(existing);page=await existing.fetch(request(existingId,tokens.read));expect(page.status).toBe(200);await page.arrayBuffer();
 const brokenId='cf-get-schema-conflict',broken=(env as unknown as Env).PRIVATE_ROOMS.getByName(brokenId);await runInDurableObject<PrivateRoom,void>(broken,(_room,ctx)=>{ctx.storage.sql.exec('CREATE TABLE unrelated_mock(id INTEGER)').toArray();});const conflict=await broken.fetch(request(brokenId));expect(conflict.status).toBe(500);await conflict.arrayBuffer();const preserved=await runInDurableObject<PrivateRoom,number>(broken,(_room,ctx)=>Number(ctx.storage.sql.exec("SELECT COUNT(*) AS n FROM sqlite_master WHERE name='unrelated_mock'").one().n));expect(preserved).toBe(1);console.log(JSON.stringify({phase:'blank-get-readonly',schema_tables:blank.userTables,metadata_keys:blank.metadataKeys,existing_get_status:page.status,conflict_status:conflict.status,unrelated_table_preserved:true}));
});
