import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {SQLiteRepository,applySQLite} from '../src/storage/sqlite';
import {recentBufferContract} from './recent-buffer-contract';
import {PrivateRoomCore} from '../src/private-core';
import {RecordCollection as C} from '../src/storage/repository';
import {privateSnapshot} from './selfhost-private-fixture';
import {TEST_BUDGET} from './selfhost-budget';
import {HttpError} from '../src/http';
import {notice} from '../src/private-state';
const origin='http://localhost:18794';
test('SQLite recent buffer atomic/count/bytes/time/restart contract',async()=>{const dir=mkdtempSync(join(tmpdir(),'toktok-recent-')),file=join(dir,'fixture.db');applySQLite(file);const repo=new SQLiteRepository(file);try{console.log(JSON.stringify(await recentBufferContract(repo)));}finally{await repo.close();rmSync(dir,{recursive:true,force:true});}});
test('new anonymous recent buffer persists across restart; legacy private stays memory; cutoff denies write atomically',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'toktok-recent-private-')),file=join(dir,'fixture.db');applySQLite(file);const repo=new SQLiteRepository(file),cores:PrivateRoomCore[]=[];let now=Date.now(),deny=false;
 const make=()=>{const core=new PrivateRoomCore({origin,repo,clock:()=>now,budget:{...TEST_BUDGET,async reserve(id,kind,amount){if(deny&&kind==='persistent_write_bytes')throw new HttpError(429,'BUDGET_EXCEEDED','fixture');await TEST_BUDGET.reserve(id,kind,amount);}}});cores.push(core);return core;};
 const call=(core:PrivateRoomCore,id:string,path:string,token:string,data?:object,method=data?'POST':'GET')=>core.fetch(new Request(origin+'/api/v1/rooms/'+id+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined}));
 try{for(const legacy of [false,true]){const id=legacy?'legacy':'recent',{snapshot,tokens}=await privateSnapshot(id,false,now);if(legacy){snapshot.notice_version='toktok-risk-v1';snapshot.creator_ack.version='toktok-risk-v1';}const core=make();await core.initialize(snapshot);
 const joined=await call(core,id,'/participants',tokens.invite,{nickname:'fictional',client_request_id:'one',notice_version:snapshot.notice_version,visibility:'private',retention_mode:notice(snapshot).retention_mode});assert.equal(joined.status,201);const token=(await joined.json() as {participant_token:string}).participant_token;
 const sent=await call(core,id,'/messages',token,{text:'fictional',client_message_id:'one'});assert.equal(sent.status,201);const first=await sent.json() as {cursor:string};core.shutdown();const cold=make();const read=await call(cold,id,'/messages',tokens.read);assert.equal(read.status,200);const page=await read.json() as {messages:{cursor:string}[]};assert.equal(page.messages.length,legacy?0:1);if(!legacy){assert.equal(page.messages[0].cursor,first.cursor);const replay=await call(cold,id,'/messages',token,{text:'fictional',client_message_id:'one'});assert.equal(replay.status,200);await replay.arrayBuffer();deny=true;const blocked=await call(cold,id,'/messages',token,{text:'blocked',client_message_id:'blocked'});assert.equal(blocked.status,429);await blocked.arrayBuffer();deny=false;const large=await call(cold,id,'/messages',token,{text:'\u0001'.repeat(10790),client_message_id:'oversized-envelope'});assert.equal(large.status,413);await large.arrayBuffer();assert.equal((await repo.transaction('room:'+id,tx=>tx.get(C.recent_buffers,'buffer')))?.count,1);const removed=await call(cold,id,'',tokens.owner,undefined,'DELETE');assert.equal(removed.status,204);assert.equal((await repo.transaction('room:'+id,tx=>tx.list(C.recent_messages,{limit:1000}))).length,0);}else assert.equal((await repo.transaction('room:'+id,tx=>tx.list(C.recent_messages,{limit:1000}))).length,0);}
 }finally{for(const core of cores)core.shutdown();await repo.close();rmSync(dir,{recursive:true,force:true});}
});

test('public recent write budget denial leaves body and sequence unchanged',async()=>{
 const {PublicRoomCore}=await import('../src/public-core'),{PUBLIC_CATALOG,PUBLIC_POLICY,PUBLIC_NOTICE,INTERNAL_IP_HEADER}=await import('../src/public-contracts');const dir=mkdtempSync(join(tmpdir(),'toktok-recent-budget-')),file=join(dir,'fixture.db');applySQLite(file);const repo=new SQLiteRepository(file);let deny=false;const core=new PublicRoomCore({repo,origin,catalog:()=>PUBLIC_CATALOG,policy:()=>({...PUBLIC_POLICY}),budget:{...TEST_BUDGET,async reserve(id,kind,amount){if(deny&&kind==='persistent_write_bytes')throw new HttpError(429,'BUDGET_EXCEEDED','fixture');await TEST_BUDGET.reserve(id,kind,amount);}}});
 const call=(path:string,body:object,token?:string)=>core.fetch(new Request(origin+'/api/public/rooms/common-room'+path,{method:'POST',headers:{'Content-Type':'application/json',[INTERNAL_IP_HEADER]:'a'.repeat(64),...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}));
 try{const grant=await core.issueOperatorGrant({room:'common-room',checked:true,risk_ack_version:PUBLIC_NOTICE,trustedIpHash:'a'.repeat(64)} as import('../src/public-contracts').ValidatedOperatorAck);assert.equal(grant.status,201);const joined=await call('/participants',{operator_grant:(grant.data as {operator_grant:string}).operator_grant,nickname:'fictional',client_request_id:'one',notice_version:PUBLIC_NOTICE,visibility:'public',retention_mode:'recent_buffer'});assert.equal(joined.status,201);const token=(await joined.json() as {lease_token:string}).lease_token;deny=true;const rejected=await call('/messages',{text:'not stored',client_message_id:'denied'},token);assert.equal(rejected.status,429);await rejected.arrayBuffer();const meta=await repo.transaction('public:common-room',async tx=>({state:await tx.get(C.recent_buffers,'buffer'),rows:await tx.list(C.recent_messages,{limit:1000})}));assert.equal(meta.state?.sequence,0);assert.equal(meta.rows.length,0);assert.equal(core.diagnostics().active_handlers,0);}finally{core.shutdown();await repo.close();rmSync(dir,{recursive:true,force:true});}
});

test('Node disk reopen and startup recover recent cleanup without touching room HTTP',async()=>{
 const {RecentBuffer}=await import('../src/recent-buffer'),{createApplication}=await import('../src/selfhost/application');const dir=mkdtempSync(join(tmpdir(),'toktok-recent-restore-')),file=join(dir,'fixture.db');applySQLite(file);let repo=new SQLiteRepository(file);let app:ReturnType<typeof createApplication>|undefined;const now=Date.now()-2000;
 try{const {snapshot,tokens}=await privateSnapshot('recent-restore',false,now);snapshot.policy.memoryRetentionMs=1000;const core=new PrivateRoomCore({origin,repo,clock:()=>now,budget:TEST_BUDGET});await core.initialize(snapshot);const request=(path:string,body:object,token:string)=>core.fetch(new Request(origin+'/api/v1/rooms/recent-restore'+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)}));const joined=await request('/participants',{nickname:'fictional',client_request_id:'one',notice_version:snapshot.notice_version,visibility:'private',retention_mode:'recent_buffer'},tokens.invite);assert.equal(joined.status,201);const token=(await joined.json() as {participant_token:string}).participant_token;const sent=await request('/messages',{text:'expired fixture',client_message_id:'one'},token);assert.equal(sent.status,201);await sent.arrayBuffer();core.shutdown();const buffer=new RecentBuffer(repo,'public:common-room'),bounds={messages:500,retentionMs:3600000,expiresAt:null};await buffer.initialize();for(let i=0;i<101;i++)await buffer.append({sender:{id:'fictional',nickname:'fixture'},text:'expired',client_message_id:String(i)},bounds,now-3600000);await repo.close();repo=new SQLiteRepository(file);assert.deepEqual(await repo.listPublicRoomIds({limit:100}),{ids:['common-room']});assert.deepEqual(await repo.listPrivateRoomIds({limit:100}),{ids:['recent-restore']});app=createApplication({origin,repo});await app.prepare();await new Promise(r=>setTimeout(r,1200));for(const scope of ['public:common-room','room:recent-restore'])assert.equal((await repo.transaction(scope,tx=>tx.list(C.recent_messages,{limit:1000}))).length,0);assert.deepEqual(await repo.listPublicRoomIds({limit:100}),{ids:[]});}finally{if(app)await app.stop();else await repo.close();rmSync(dir,{recursive:true,force:true});}
});
