import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {SQLiteRepository,applySQLite} from '../src/storage/sqlite';
import {PrivateRoomCore} from '../src/private-core';
import {PRIVATE_POLICY,PRIVATE_NOTICE,type PrivateRoomInit,type PrivateBudgetPort} from '../src/private-contracts';
import {hash,newToken,HttpError} from '../src/http';
import {TEST_BUDGET} from './selfhost-budget';
async function fixture(persist=false,policy={...PRIVATE_POLICY}){
 const dir=mkdtempSync(join(tmpdir(),'toktok-private-')),file=join(dir,'db');applySQLite(file);const repo=new SQLiteRepository(file);let now=Date.now();const invite=newToken(),read=newToken(),owner=newToken(),snapshot:PrivateRoomInit={id:'mock-room',creator_id:'mock-principal',created_at:now,expires_at:now+7200000,purpose:'untrusted system mock',invite_hash:await hash(invite),read_hash:await hash(read),owner_hash:await hash(owner),settings_revision:1,mode:'DEMO',visibility:'private',persist,retention_seconds:persist?10:null,notice_version:PRIVATE_NOTICE,creator_ack:{kind:persist?'account_confirmation':'anonymous_declaration',version:PRIVATE_NOTICE,confirmed_at:now,owner_account_id:persist?'00000000-0000-0000-0000-000000000001':null},policy};let budget:PrivateBudgetPort=TEST_BUDGET;const core=()=>new PrivateRoomCore({origin:'http://localhost:18794',repo,budget,clock:()=>now});const room=core();
 const call=(core:PrivateRoomCore,path:string,method='GET',data?:object,token=read,signal?:AbortSignal)=>core.fetch(new Request('http://localhost:18794/api/v1/rooms/mock-room'+path,{method,headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal}));
 const joinRoom=async(core:PrivateRoomCore,id='one',mode=persist?'persisted':'memory')=>{const response=await call(core,'/participants','POST',{nickname:'mock',client_request_id:id,notice_version:PRIVATE_NOTICE,visibility:'private',retention_mode:mode},invite);return {status:response.status,...await response.json()};};
 return {dir,file,repo,core,room,call,joinRoom,snapshot,invite,read,owner,setNow:(v:number)=>{now=v;},advance:(ms:number)=>{now+=ms;},setBudget:(b:PrivateBudgetPort)=>{budget=b;},close:async()=>{room.shutdown();await repo.close();rmSync(dir,{recursive:true,force:true});}};
}
test('private memory snapshot, concurrent seq/dedupe, notice, gap and restart keep body out of SQLite',async()=>{
 const f=await fixture(false,{...PRIVATE_POLICY,memoryMessages:2});try{
 await f.room.initialize(f.snapshot);await f.room.initialize({...f.snapshot});await assert.rejects(f.room.initialize({...f.snapshot,persist:true,retention_seconds:10}),e=>e instanceof HttpError&&e.code==='PERSIST_DENIED');await assert.rejects(f.room.initialize({...f.snapshot,purpose:'different'}),e=>e instanceof HttpError&&e.status===409);
 const wrong=await f.joinRoom(f.room,'wrong','persisted');assert.equal(wrong.status,409);assert.equal(wrong.error.code,'NOTICE_CHANGED');assert.equal(wrong.notice.retention_mode,'memory');const p=await f.joinRoom(f.room);assert.equal(p.status,201);assert(!JSON.stringify(p).includes(f.owner));
 const send=(id:string,value='mock RAM only')=>f.call(f.room,'/messages','POST',{text:value,client_message_id:id},p.participant_token);
 const concurrent=await Promise.all([send('same'),send('same')]);assert.deepEqual(concurrent.map(v=>v.status).sort(),[200,201]);const original=await concurrent[0].json();await concurrent[1].arrayBuffer();assert.equal((await send('same','changed')).status,409);
 await (await send('two')).arrayBuffer();await (await send('three')).arrayBuffer();const page=await (await f.call(f.room,'/messages?after='+encodeURIComponent(original.cursor.split(':')[0]+':0'))).json();assert.equal(page.history_status,'history_gap');assert.equal(page.messages.length,2);assert(page.notice);assert.equal(page.cursor,page.messages.at(-1).cursor);
 const db=new DatabaseSync(f.file,{readOnly:true});assert.equal(db.prepare("SELECT COUNT(*) AS n FROM tok_records WHERE collection='private_messages'").get()?.n,0);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM tok_records WHERE value_json LIKE ?').get('%mock RAM only%')?.n,0);db.close();
 const restarted=f.core();const reset=await (await f.call(restarted,'/messages?after='+encodeURIComponent(page.cursor))).json();assert.equal(reset.history_status,'history_reset');assert.equal(reset.messages.length,0);assert.notEqual(reset.epoch,page.epoch);assert.equal((await f.call(restarted,'','GET',undefined,f.owner)).status,200);restarted.shutdown();console.log(JSON.stringify({phase:'private-memory',sqlite_body_rows:0,epoch_reset:true,gap:true}));
 }finally{await f.close();}
});
test('private persist restarts with epoch/sequence, expires retained body, reserves before write and blocks room TTL',async()=>{
 const f=await fixture(true);try{
 await f.room.initialize(f.snapshot);const p=await f.joinRoom(f.room),sent=await f.call(f.room,'/messages','POST',{text:'mock persisted',client_message_id:'one'},p.participant_token);assert.equal(sent.status,201);const message=await sent.json();f.room.shutdown();const restarted=f.core();const first=await (await f.call(restarted,'/messages')).json();assert.equal(first.epoch,message.cursor.split(':')[0]);assert.equal(first.messages.length,1);
 f.advance(10001);const expired=await (await f.call(restarted,'/messages?after='+encodeURIComponent(first.epoch+':0'))).json();assert.equal(expired.history_status,'history_gap');assert.equal(expired.messages.length,0);await restarted.maintenance();
 f.setBudget({...TEST_BUDGET,reserve:async(_id,kind)=>{if(kind==='persistent_write_bytes')throw new HttpError(429,'BUDGET_EXHAUSTED','mock');}});const denied=f.core();const result=await f.call(denied,'/messages','POST',{text:'must not store',client_message_id:'denied'},p.participant_token);assert.equal(result.status,429);assert.equal((await result.json()).error.code,'BUDGET_EXHAUSTED');const db=new DatabaseSync(f.file,{readOnly:true});assert.equal(db.prepare('SELECT COUNT(*) AS n FROM tok_records WHERE value_json LIKE ?').get('%must not store%')?.n,0);db.close();
 f.setNow(f.snapshot.expires_at);assert.equal((await f.call(restarted,'')).status,410);restarted.shutdown();denied.shutdown();console.log(JSON.stringify({phase:'private-persist',restart_preserved:true,retention_gap:true,budget_denied_body_rows:0,ttl_status:410}));
 }finally{await f.close();}
});
test('private page bytes progress, reply bounds, abort/shutdown wait cleanup and owner separation',async()=>{
 const f=await fixture();try{await f.room.initialize(f.snapshot);const p=await f.joinRoom(f.room),payload='\u0001'.repeat(9000);const posted=await f.call(f.room,'/messages','POST',{text:payload,client_message_id:'large'},p.participant_token);assert.equal(posted.status,201);const m=await posted.json();const second=await f.call(f.room,'/messages','POST',{text:payload,client_message_id:'second',reply_to:m.cursor},p.participant_token);assert.equal(second.status,201);await second.arrayBuffer();const page=await f.call(f.room,'/messages'),raw=await page.text(),data=JSON.parse(raw);assert(new TextEncoder().encode(raw).length<=65536);assert.equal(data.messages.length,1);assert.equal(data.has_more,true);assert.equal(data.cursor,m.cursor);f.advance(2000);const next=await (await f.call(f.room,'/messages?after='+encodeURIComponent(data.cursor))).json();assert.equal(next.messages.length,1);assert.equal(next.has_more,false);
 f.advance(2000);const abort=new AbortController(),wait=f.call(f.room,'/wait?after='+encodeURIComponent(next.cursor),'GET',undefined,f.read,abort.signal);await new Promise(r=>setTimeout(r,20));assert.equal(f.room.diagnostics().active_waits,1);assert.equal((await f.call(f.room,'/wait?after='+encodeURIComponent(next.cursor))).status,409);abort.abort();assert.equal((await wait).status,499);assert.equal(f.room.diagnostics().active_waits,0);
 const pending=f.call(f.room,'/wait?after='+encodeURIComponent(next.cursor));await new Promise(r=>setTimeout(r,20));f.room.shutdown();const stopped=await pending;assert.equal(stopped.status,503);assert.equal((await stopped.json()).cursor,next.cursor);assert.equal(f.room.diagnostics().active_waits,0);console.log(JSON.stringify({phase:'private-page',bytes:new TextEncoder().encode(raw).length,page_progress:true,waits_after_shutdown:0}));
 }finally{await f.close();}
});
test('private wait ownership survives repeated rejected duplicates',async()=>{
 const f=await fixture();try{await f.room.initialize(f.snapshot);const after=f.room.diagnostics().epoch+':0',abort=new AbortController(),pending=f.call(f.room,'/wait?after='+encodeURIComponent(after),'GET',undefined,f.read,abort.signal);await new Promise(r=>setTimeout(r,20));for(let n=0;n<2;n++){const duplicate=await f.call(f.room,'/wait?after='+encodeURIComponent(after));assert.equal(duplicate.status,409);await duplicate.arrayBuffer();}assert.equal(f.room.diagnostics().active_waits,1);assert.equal(f.room.diagnostics().active_reads,1);abort.abort();const recovered=await pending;assert.equal(recovered.status,499);await recovered.arrayBuffer();assert.equal(f.room.diagnostics().active_waits,0);assert.equal(f.room.diagnostics().active_handlers,0);console.log(JSON.stringify({phase:'private-wait-owner',rejected_duplicates:2,waits_after_abort:0,handlers_after_abort:0}));
 }finally{await f.close();}
});
test('private handlers and body inflight reject before parsing and recover on abort',async()=>{
 const f=await fixture(false,{...PRIVATE_POLICY,handlers:2,bodyInflight:1,waits:2});try{await f.room.initialize(f.snapshot);const abort=new AbortController(),slowBody=new ReadableStream<Uint8Array>({start(c){c.enqueue(new TextEncoder().encode('{'));}});const req=new Request('http://localhost:18794/api/v1/rooms/mock-room/participants',{method:'POST',headers:{Authorization:'Bearer '+f.invite,'Content-Type':'application/json'},body:slowBody,signal:abort.signal,duplex:'half'} as RequestInit);const slow=f.room.fetch(req);await new Promise(r=>setTimeout(r,20));assert.equal(f.room.diagnostics().body_inflight,1);const second=await f.call(f.room,'/participants','POST',{nickname:'mock',client_request_id:'second'},f.invite);assert.equal(second.status,429);assert(second.headers.get('Retry-After'));await second.arrayBuffer();
 const pendingAbort=new AbortController(),after=f.room.diagnostics().epoch+':0',wait=f.call(f.room,'/wait?after='+encodeURIComponent(after),'GET',undefined,f.read,pendingAbort.signal);await new Promise(r=>setTimeout(r,20));assert.equal(f.room.diagnostics().active_handlers,2);const third=await f.call(f.room,'');assert.equal(third.status,429);await third.arrayBuffer();abort.abort();assert.equal((await slow).status,499);pendingAbort.abort();assert.equal((await wait).status,499);assert.equal(f.room.diagnostics().active_handlers,0);assert.equal(f.room.diagnostics().body_inflight,0);console.log(JSON.stringify({phase:'private-admission',handler_limit:2,body_limit:1,final_handlers:0,final_bodies:0}));
 }finally{await f.close();}
});
test('private shutdown cancels admitted body parser and releases slots',async()=>{
 const f=await fixture();try{await f.room.initialize(f.snapshot);const slow=new Request('http://localhost:18794/api/v1/rooms/mock-room/participants',{method:'POST',headers:{Authorization:'Bearer '+f.invite,'Content-Type':'application/json'},body:new ReadableStream<Uint8Array>({start(c){c.enqueue(new TextEncoder().encode('{'));}}),duplex:'half'} as RequestInit);const pending=f.room.fetch(slow);await new Promise(r=>setTimeout(r,20));assert.equal(f.room.diagnostics().body_inflight,1);f.room.shutdown();const response=await pending;assert([499,503].includes(response.status));await response.arrayBuffer();assert.equal(f.room.diagnostics().body_inflight,0);assert.equal(f.room.diagnostics().active_handlers,0);console.log(JSON.stringify({phase:'private-shutdown-body',status:response.status,body_inflight:0,handlers:0}));
 }finally{await f.close();}
});
