import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {SQLiteRepository,applySQLite} from '../src/storage/sqlite';
import {RecordCollection as C} from '../src/storage/repository';
import {PrivateRoomCore} from '../src/private-core';
import {messageKey} from '../src/private-state';
import {privateSnapshot} from './selfhost-private-fixture';
import {TEST_BUDGET} from './selfhost-budget';
test('closed private wait serves unread first then 410; owner delete clears bounded body batches before TTL',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'toktok-lifecycle-')),file=join(dir,'test.sqlite');applySQLite(file);const repo=new SQLiteRepository(file),cores:PrivateRoomCore[]=[];let now=Date.now();const make=()=>{const c=new PrivateRoomCore({origin:'http://localhost:18794',repo,budget:TEST_BUDGET,clock:()=>now});cores.push(c);return c;};
 const call=(c:PrivateRoomCore,id:string,path:string,token:string,method='GET',data?:object)=>c.fetch(new Request('http://localhost:18794/api/v1/rooms/'+id+path,{method,headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined}));
 try{
 const id='closed-history',{snapshot,tokens}=await privateSnapshot(id,false,now),core=make();await core.initialize(snapshot);const joined=await call(core,id,'/participants',tokens.invite,'POST',{nickname:'mock',client_request_id:'join',notice_version:snapshot.notice_version,visibility:'private',retention_mode:'memory'});assert.equal(joined.status,201);const {participant_token}=await joined.json() as {participant_token:string};const sent=await call(core,id,'/messages',participant_token,'POST',{text:'mock unread',client_message_id:'one'});assert.equal(sent.status,201);const {cursor}=await sent.json() as {cursor:string};const closed=await call(core,id,'/close',tokens.owner,'POST');assert.equal(closed.status,200);await closed.arrayBuffer();
 const unread=await call(core,id,'/wait',tokens.read);assert.equal(unread.status,200);assert.equal((await unread.json() as {messages:object[]}).messages.length,1);now+=2000;const empty=await call(core,id,'/wait?after='+encodeURIComponent(cursor)+'&timeout=0',tokens.read);assert.equal(empty.status,410);assert.equal((await empty.json() as {error:{code:string}}).error.code,'ROOM_CLOSED');const history=await call(core,id,'/messages',tokens.read);assert.equal(history.status,200);await history.arrayBuffer();
 const pendingId='closed-pending',pendingSnapshot=await privateSnapshot(pendingId,false,now),pendingCore=make();await pendingCore.initialize(pendingSnapshot.snapshot);const waiting=call(pendingCore,pendingId,'/wait?after='+pendingCore.diagnostics().epoch+':0',pendingSnapshot.tokens.read);for(let n=0;n<40&&!pendingCore.diagnostics().active_waits;n++)await new Promise(r=>setTimeout(r,1));assert.equal(pendingCore.diagnostics().active_waits,1);const closeWake=await call(pendingCore,pendingId,'/close',pendingSnapshot.tokens.owner,'POST');assert.equal(closeWake.status,200);await closeWake.arrayBuffer();const woke=await waiting;assert.equal(woke.status,410);assert.equal((await woke.json() as {error:{code:string}}).error.code,'ROOM_CLOSED');assert.equal(pendingCore.diagnostics().active_waits,0);
 const deletedId='owner-delete',deletedSnapshot=await privateSnapshot(deletedId,true,now),initial=make();await initial.initialize(deletedSnapshot.snapshot);await repo.transaction('room:'+deletedId,async tx=>{const state=(await tx.get(C.private_rooms,deletedId))!;state.body_count=201;state.sequence=201;await tx.put(C.private_rooms,deletedId,state);for(let seq=1;seq<=201;seq++){const dedupe='d:fixture:'+seq;await tx.put(C.private_messages,messageKey(seq),{sequence:seq,cursor:String(state.epoch)+':'+seq,sender:{id:'mock',nickname:'mock'},text:'mock body',client_message_id:String(seq),reply_to:null,created_at:new Date(now).toISOString(),dedupe_key:dedupe});await tx.put(C.private_messages,dedupe,{sequence:seq});}});initial.shutdown();const deletion=make(),result=await call(deletion,deletedId,'',deletedSnapshot.tokens.owner,'DELETE');assert.equal(result.status,204);
 const count=()=>repo.transaction('room:'+deletedId,async tx=>({body:(await tx.list(C.private_messages,{prefix:'m:',limit:1000})).length,dedupe:(await tx.list(C.private_messages,{prefix:'d:',limit:1000})).length}));assert.deepEqual(await count(),{body:101,dedupe:101});assert.equal((await call(deletion,deletedId,'/messages',deletedSnapshot.tokens.read)).status,410);const first=await deletion.maintenance(deletedId) as {next_maintenance_at:number|null};assert.deepEqual(await count(),{body:1,dedupe:1});assert.equal(first.next_maintenance_at,now+1000);now+=1000;const last=await deletion.maintenance(deletedId) as {next_maintenance_at:number|null};assert.deepEqual(await count(),{body:0,dedupe:0});assert.equal(last.next_maintenance_at,null);
 console.log(JSON.stringify({phase:'private-close-delete',unread_status:200,closed_empty_wait:empty.status,pending_close_wait:woke.status,closed_history:history.status,delete_status:result.status,batches:[100,100,1],final_body_rows:0,final_dedupe_rows:0,pending_waits:0}));
 }finally{for(const c of cores)c.shutdown();await repo.close();rmSync(dir,{recursive:true,force:true});}
});
