import {it,expect} from 'vitest';
import {createRoomController} from '../public/shared/newroom-controller.js';
const anon={authenticated:false,role:'anonymous',entitlements:{can_create_private:false,can_persist_private:false},owner_ack:null};
const member={...anon,authenticated:true,role:'member',entitlements:{can_create_private:true,can_persist_private:true}};
const config={mode:'DEMO',enabled:true,limits:{private:{anonymousEnabled:true,defaultPersist:false,anonymousDefaultTtlSeconds:3600,anonymousMaxTtlSeconds:86400,authenticatedDefaultTtlSeconds:86400,authenticatedMaxTtlSeconds:604800,defaultRetentionSeconds:86400,maxRetentionSeconds:604800}}};
const context={nonce:'fictional-nonce',notice_version:'toktok-risk-v2',expires_at:'2026-10-04T00:00:00.000Z',authenticated:false,can_persist_private:false};
const result={room:{id:'fictional-room',purpose:'🌱'.repeat(1000),status:'open',visibility:'private',retention_mode:'recent_buffer',retention_seconds:3600,recent_buffer:{max_messages:500,max_bytes:2097152},notice_version:'toktok-risk-v2',expires_at:'2026-10-04T00:00:00.000Z'},invite_url:'https://toktok.example/r/fictional-room/fictional-invite',read_url:'https://toktok.example/r/fictional-room/fictional-read',owner_token:'fictional-owner-secret'};
it('keeps anonymous recent buffer/long-term default OFF and requires explicit risk before context/grant/create; accepts Unicode1000',async()=>{
 let state;const calls=[];const c=createRoomController({effects:{getConfig:async()=>config,getSession:async()=>anon,createContext:async()=>{calls.push('context');return context;},creationGrant:async input=>{calls.push(input);return {creation_grant:'fictional-grant',notice_version:'toktok-risk-v2',expires_at:context.expires_at};},createRoom:async input=>{calls.push(input);return result;}},paint:v=>state=v,newRequestId:()=> 'same-create-id'});
 await c.load();expect(state.persist).toBe(false);c.set('purpose','🌱'.repeat(1000));c.set('persist',true);expect(state.persist).toBe(false);await c.submit();expect(calls).toEqual([]);c.set('checked',true);await c.submit();expect(calls[0]).toBe('context');expect(calls[1]).toEqual({nonce:'fictional-nonce',risk_ack:true});expect(calls[2]).toMatchObject({purpose:result.room.purpose,persist:false,ttl_seconds:3600,client_request_id:'same-create-id',creation_grant:'fictional-grant'});expect(state.status).toBe('created');expect(JSON.stringify(state)).not.toContain('fictional-owner-secret');expect(c.ownerMaterial()).toBe('fictional-owner-secret');c.dispose();expect(c.ownerMaterial()).toBe(null);
});
it('keeps the same request and grant on pending/lost responses and never invents recovery or a second room',async()=>{
 let state,count=0;const ids=[];const c=createRoomController({effects:{getConfig:async()=>config,getSession:async()=>member,createContext:async()=>({...context,authenticated:true,can_persist_private:true}),creationGrant:async()=>({creation_grant:'fictional-grant',notice_version:context.notice_version,expires_at:context.expires_at}),createRoom:async input=>{ids.push(input);throw Object.assign(Error(),{code:++count===1?'CREATE_PENDING':'CREATE_RESULT_NOT_RECOVERABLE',status:409,room_id:'fictional-room',retryAfter:'0'});}},paint:v=>state=v,newRequestId:()=> 'same-create-id'});
 await c.load();c.set('purpose','가상 방');c.set('checked',true);await c.submit();expect(state.error.room_id).toBe('fictional-room');expect(state.locked).toBe(true);c.set('purpose','바뀐 이름');expect(state.purpose).toBe('가상 방');await c.submit();expect(ids[1]).toEqual(ids[0]);expect(state.error.code).toBe('CREATE_RESULT_NOT_RECOVERABLE');await c.submit();expect(ids).toHaveLength(2);expect(state.status).not.toBe('created');c.dispose();
});
it('enforces retention<=actual TTL and server context persistence without using client role as approval',async()=>{
 let state,created=0;const c=createRoomController({effects:{getConfig:async()=>config,getSession:async()=>member,createContext:async()=>({...context,authenticated:true,can_persist_private:false}),creationGrant:async()=>{throw Error('must not grant');},createRoom:async()=>{created++;}},paint:v=>state=v});
 await c.load();expect(state.persist).toBe(false);c.set('purpose','가상 방');c.set('persist',true);c.set('retention_seconds',604800);c.set('checked',true);await c.submit();expect(state.error.code).toBe('RETENTION_EXCEEDS_TTL');c.set('retention_seconds',86400);await c.submit();expect(state.error.code).toBe('PERSIST_DENIED');expect(created).toBe(0);c.dispose();
});
it('rejects unsafe share URLs and a mismatched returned persistence snapshot instead of painting success',async()=>{
 for(const bad of [{...result,invite_url:'javascript:alert(1)'},{...result,room:{...result.room,retention_mode:'persisted',retention_seconds:86400}}]){
  let state;const c=createRoomController({origin:'https://toktok.example',effects:{getConfig:async()=>config,getSession:async()=>anon,createContext:async()=>context,creationGrant:async()=>({creation_grant:'fictional-grant',notice_version:context.notice_version,expires_at:context.expires_at}),createRoom:async()=>bad},paint:v=>state=v,newRequestId:()=> 'fictional-request'});
  await c.load();c.set('purpose','가상 방');c.set('checked',true);await c.submit();expect(state.status).toBe('uncertain');expect(state.error.code).toBe('INVALID_CREATE_RESPONSE');expect(c.ownerMaterial()).toBe(null);c.dispose();
 }
});
