// Dependency-free mocked-DOM behavior tests. Not a browser or visual accessibility audit.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const root=fs.existsSync(path.join(__dirname,'dist'))?path.join(__dirname,'dist'):__dirname;const noop=()=>{},els=new Map(),timers=[];const app={innerHTML:'',prepend:noop,insertAdjacentHTML:noop};let closed=0;function el(k){if(k==='#app')return app;if(!els.has(k))els.set(k,{value:'',dataset:{},fields:{},insertAdjacentHTML:noop,prepend:noop,showModal:noop,close:()=>closed++,focus:noop,select:noop,scrollIntoView:noop,addEventListener:noop,classList:{add:noop,remove:noop},setAttribute:noop,textContent:''});return els.get(k)}class FD{constructor(form){this.f=form.fields}get(k){return this.f[k]??null}}const c={document:{querySelector:el,querySelectorAll:()=>[],body:{className:''},addEventListener:noop},location:{hash:''},history:{replaceState:(_a,_b,s)=>c.location.hash=s},scrollTo:noop,scrollY:0,setTimeout:f=>(timers.push(f),timers.length),setInterval:()=>1,clearTimeout:noop,console,AbortController,navigator:{},FormData:FD,addEventListener:noop};c.window=c;vm.createContext(c);const run=s=>vm.runInContext(s,c);run(fs.readFileSync(path.join(root,'app.js'),'utf8'));run(fs.readFileSync(path.join(root,'design-contract.js'),'utf8'));run(fs.readFileSync(path.join(root,'experience.js'),'utf8').replace('window.toktokDemoState=state;','window.__test={handle,changed,reviewSave,validateSettings};window.toktokDemoState=state;'));const route=r=>{c.location.hash='#'+r;run('render()')};const submit=(id,fields)=>{el(id).fields=fields;el(id).onsubmit({preventDefault:noop})};const act=(a,b={})=>run(`__test.handle(${JSON.stringify(a)},${JSON.stringify(b)})`);const state=c.toktokDemoState;
route('verify');submit('#xVerifyForm',{otp:'123456'});assert.equal(state.signed,false,'direct challenge bypass');console.log('PASS: direct verify without challenge rejected');
route('signup');assert(!app.innerHTML.includes('data-x="accept-invite"'),'missing invite bypass');route('invite/anything');assert(app.innerHTML.includes('초대를 찾을 수 없어요'));console.log('PASS: missing and unknown invites rejected');
route('invite/demo');submit('#inviteCodeForm',{inviteCode:'00000000-0000-4000-8000-000000000001'});run('render()');act('accept-invite');run('render()');submit('#xAuthForm',{email:'friend@example.com'});run('render()');submit('#xVerifyForm',{otp:'111111'});assert.equal(state.signed,false);act('otp-expired');submit('#xVerifyForm',{otp:'123456'});assert.equal(state.signed,false);act('resend');submit('#xVerifyForm',{otp:'123456'});assert.equal(state.signed,true);assert.equal(state.invites[0].status,'used');route('invite/demo');submit('#inviteCodeForm',{inviteCode:'00000000-0000-4000-8000-000000000001'});assert(state.inviteError.includes('이미 사용한 초대'));assert(state.invitedAccount);route('new-room');assert(!app.innerHTML.includes('DEMO에서는 가입해도'));console.log('PASS: visible code validation; invited DEMO account eligible for opt-in persistence');console.log('PASS: wrong/expired OTP rejected; resend succeeds; invite consumed');
state.mode='HOSTED';route('new-room');state.persist=true;state.retention=30;run('render()');assert(app.innerHTML.includes('30일 동안 보관'));submit('#xRoomForm',{name:'아주 긴 방 이름으로 확인하는 우리의 다음 작고 편안한 대화',ttl:'7일',persist:'on',retention:'30',ownerRisk:'on'});run('render()');assert.equal(state.createdRoom.ttl,'7일');route('room/new');assert.equal(run('ttl'),'7일');assert.equal(run('created'),true);assert.equal(run('roomName'),state.createdRoom.name);route('room/coffee');assert.equal(run('roomName'),'조금 다른 아이디어 한 잔.');route('new-room');assert.equal(state.persist,false);assert(app.innerHTML.includes('value="off" checked'));console.log('PASS: immutable new-room retention/TTL/name, correct room route and new opt-in resets');
route('public/empty');act('open-grant');run('render()');assert(app.innerHTML.includes('<dd>오늘의 작은 발견</dd>'));act('allow-grant');assert(!state.grants.empty);state.risk=true;act('allow-grant');assert(state.grants.empty);route('public/garden');assert.equal(state.grant,false);route('public/empty');act('revoke-grant');assert(!state.grants.empty);console.log('PASS: risk and grant separate; room targeting isolated; revocation works');
state.role='admin';route('admin/public');run('toktokSettings.draft().publicRooms=10');run('__test.reviewSave()');act('confirm-save',{disabled:false,textContent:''});run('toktokSettings.draft().publicRooms=20');const saveTimer=timers.at(-1);saveTimer();assert.equal(c.toktokSettings.saved().publicRooms,10);console.log('PASS: async save uses reviewed snapshot');
run('toktokSettings.draft().resend=20');assert(c.toktokSettings.validate().includes('120'));console.log('PASS: unsafe email resend rejected');

route('welcome');assert.equal(c.location.hash,'#home');assert(app.innerHTML.includes('home-hero'));assert(!app.innerHTML.includes('journey-grid'));console.log('PASS: welcome aliases the single canonical landing');

const contract=require(path.join(root,'design-contract.js'));assert.equal(new Set(contract.routes).size,contract.routes.length);for(const e of contract.flows.edges){assert(contract.flows.nodes.some(n=>n.id===e.from));assert(contract.flows.nodes.some(n=>n.id===e.to))}for(const n of contract.flows.nodes)assert(contract.routes.includes(n.route));state.role='admin';state.signed=true;for(const r of ['admin/design-components','admin/design-dialogs','admin/design-flows']){route(r);assert(app.innerHTML.includes('<main'));assert(!app.innerHTML.includes('undefined'))}state.role='member';route('admin/design-flows');assert(app.innerHTML.includes('관리자 권한이 없어요'));console.log('PASS: registry graph references, three shared QA surfaces, non-admin restriction');

const sourceText=['app.js','experience.js','selects.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');for(const component of contract.components)assert(sourceText.includes(component.renderer),'Unresolved component '+component.id);assert.equal(new Set(contract.dialogues.map(d=>d.id)).size,contract.dialogues.length);state.role='admin';state.signed=true;for(const r of contract.routes){state.dirty=false;route(r);assert(app.innerHTML.includes('<main'),'No view '+r);assert(!app.innerHTML.includes('undefined'),'Undefined content '+r)}console.log('PASS: registered component references, unique dialogues and '+contract.routes.length+' registered route renders');
