import {HttpError,bearer,hash,newToken,text,queryInt,fail,json} from './http';
import {publicError,PublicError,publicBody,cancelUnusedRequestBody} from './public-http';
import {serviceMetadata,AGENT_SAFETY_NOTICE,untrustedMarkdown} from './public-safety';
import {RecordCollection as C,type RecordValue,type RecordTransaction} from './storage/repository';
import {CoreBudget,type ReservationContext} from './runtime/budget';
import {RoomQueue} from './runtime/room-queue';
import {PRIVATE_NOTICE,type PrivateRoomInit,type PrivateCoreOptions,type PrivateMessage,type PrivateParticipant} from './private-contracts';
import {initSnapshot,notice,roomView,messageKey,type PrivateState} from './private-state';
import {privatePage,parsePrivateCursor} from './private-page';
class NoticeChanged extends HttpError {constructor(readonly notice:object){super(409,'NOTICE_CHANGED','현재 보관 조건을 확인하세요.');}}
interface Cap {role:'invite'|'read'|'owner'|'participant';hash:string;sender?:PrivateParticipant;}
interface StoredMessage extends PrivateMessage {dedupe_key:string;}
interface Waiter {wake:()=>void;cursor?:string;}
const record=(value:object)=>JSON.parse(JSON.stringify(value)) as RecordValue;
const limited=(ms=1000):never=>{throw new PublicError(429,'RATE_LIMITED','방 요청 한도를 초과했습니다.',Math.max(1,Math.ceil(ms)));};
export class PrivateRoomCore {
 private handlers=0;private bodies=0;private bodyControllers=new Set<AbortController>();private id?:string;private state?:PrivateState;private stopped=false;private readonly queue=new RoomQueue();private readonly clock:()=>number;private readonly budget:CoreBudget;
 private ring:PrivateMessage[]=[];private waiters=new Map<string,Waiter>();private reading=new Set<string>();private lastRead=new Map<string,number>();private acceptedAt:{at:number;sender:string}[]=[];
 private joinResults=new Map<string,{digest:string;token:string;sender:{id:string;nickname:string}}>();
 constructor(private readonly options:PrivateCoreOptions){this.clock=options.clock??(()=>Date.now());this.budget=new CoreBudget(options.budget,this.clock);}
 private bind(id:string){if(!/^[a-zA-Z0-9_-]{1,128}$/.test(id))fail(404,'NOT_FOUND','방이 없습니다.');if(this.id&&this.id!==id)fail(403,'ROOM_MISMATCH','방이 다릅니다.');this.id=id;}
 private scope(){return 'room:'+this.id!;}
 private async load():Promise<PrivateState>{if(!this.state){const value=await this.options.repo.transaction(this.scope(),tx=>tx.get(C.private_rooms,this.id!));if(!value)fail(404,'NOT_FOUND','방이 없습니다.');this.state=value as unknown as PrivateState;if(!this.state.snapshot.persist){this.state.epoch=crypto.randomUUID();this.state.sequence=0;this.state.storage_first=1;this.state.body_count=0;}}return this.state;}
 private live(open=false):PrivateState {if(this.stopped)fail(503,'ROOM_SHUTDOWN','서버가 종료 중입니다. 다시 연결하세요.');const s=this.state!;if(this.clock()>=s.snapshot.expires_at||s.status==='deleted')fail(410,'ROOM_GONE','방이 만료되었거나 삭제되었습니다.');if(open&&s.status!=='open')fail(410,'ROOM_CLOSED','종료된 방입니다.');return s;}
 private async save(tx:RecordTransaction,state:PrivateState){const stored=record({...state,...(!state.snapshot.persist?{epoch:'',sequence:0,storage_first:1,body_count:0}:{}),persist_authorized:state.snapshot.persist,retention_mode:state.snapshot.persist?'persist':'memory'});await tx.put(C.private_rooms,this.id!,stored);}
 async initialize(input:PrivateRoomInit):Promise<object>{this.bind(input.id);const prepared=await initSnapshot(input);const operation=await this.budget.admit();return this.queue.run(async()=>{
 const state=await this.options.repo.transaction(this.scope(),async tx=>{const old=await tx.get(C.private_rooms,this.id!);if(old){const existing=old as unknown as PrivateState;if(existing.init_digest!==prepared.digest)fail(409,'INITIALIZATION_CONFLICT','다른 생성 snapshot으로 다시 초기화할 수 없습니다.');return existing;}
 if(this.clock()>=prepared.snapshot.expires_at)fail(410,'ROOM_GONE','방의 절대 만료 시각이 지났습니다.');const created:PrivateState={snapshot:prepared.snapshot,init_digest:prepared.digest,status:'open',epoch:crypto.randomUUID(),sequence:0,storage_first:1,body_count:0,participants:[]};await this.save(tx,created);return created;});
 if(!this.state){this.state=state;if(!state.snapshot.persist&&state.epoch==='')this.state.epoch=crypto.randomUUID();}const result={service:serviceMetadata(['room.purpose']),room:roomView(this.state)};await this.budget.reserve(operation,'response_bytes',new TextEncoder().encode(JSON.stringify(result)).length);return result;
 });}
 private capability(fingerprint:string):Cap {const s=this.live().snapshot;if(fingerprint===s.invite_hash)return {role:'invite',hash:fingerprint};if(fingerprint===s.read_hash)return {role:'read',hash:fingerprint};if(fingerprint===s.owner_hash)return {role:'owner',hash:fingerprint};const sender=this.state!.participants.find(p=>p.token_hash===fingerprint);if(sender)return {role:'participant',hash:fingerprint,sender};return fail(403,'CAPABILITY_DENIED','방 권한이 없습니다.');}
 private require(cap:Cap,role:Cap['role']){if(cap.role!==role)fail(403,'CAPABILITY_DENIED','이 동작에 필요한 권한이 없습니다.');}
 private wake(){for(const waiter of this.waiters.values())waiter.wake();}
 private pruneMemory(){const s=this.state!,now=this.clock();this.ring=this.ring.filter(m=>now-Date.parse(m.created_at)<s.snapshot.policy.memoryRetentionMs).slice(-s.snapshot.policy.memoryMessages);this.acceptedAt=this.acceptedAt.filter(v=>now-v.at<60000);}
 private async firstLive(tx:RecordTransaction,s:PrivateState):Promise<number>{let low=s.storage_first,high=s.sequence+1;const cutoff=this.clock()-s.snapshot.retention_seconds!*1000;while(low<high){const mid=Math.floor((low+high)/2),row=await tx.get(C.private_messages,messageKey(mid));if(row&&Date.parse(row.created_at as string)>cutoff)high=mid;else low=mid+1;}return low;}
 private async page(after:string|undefined,limit:number){const s=this.live();this.pruneMemory();let first=this.ring[0]?.sequence??s.sequence+1,rows=this.ring;
 if(s.snapshot.persist){const selected=await this.options.repo.transaction(this.scope(),async tx=>{first=await this.firstLive(tx,s);const cursor=parsePrivateCursor(after,s.epoch,s.sequence);const initial=after===undefined||cursor.status!=='ok'||cursor.sequence<first-1;const start=initial?Math.max(first-1,s.sequence-s.snapshot.policy.firstWindowMessages):Math.max(first-1,cursor.sequence);return tx.list(C.private_messages,{prefix:'m:',after:messageKey(start),limit:initial?s.snapshot.policy.firstWindowMessages:limit+1});});rows=selected.map(r=>{const {dedupe_key:_key,...m}=r.value;return m as unknown as PrivateMessage;}).filter(m=>this.clock()-Date.parse(m.created_at)<s.snapshot.retention_seconds!*1000);}
 return privatePage(rows,s.epoch,s.sequence,first,after,limit,s.snapshot.policy,this.clock(),s.status,notice(s.snapshot));}
 private async join(request:Request){const input=await this.parseBody(request,['nickname','client_request_id','notice_version','visibility','retention_mode']);const nickname=text(input.nickname,1,64),requestId=text(input.client_request_id,1,128),digest=await hash(JSON.stringify([nickname,input.notice_version,input.visibility,input.retention_mode])),requestFingerprint=await hash(requestId),token=newToken(),fingerprint=await hash(token);
 return this.queue.run(async()=>{const s=this.live(true);if(input.notice_version!==PRIVATE_NOTICE||input.visibility!=='private'||input.retention_mode!==(s.snapshot.persist?'persisted':'memory'))throw new NoticeChanged(notice(s.snapshot));
 const cached=this.joinResults.get(requestId);if(cached){if(cached.digest!==digest)fail(409,'IDEMPOTENCY_CONFLICT','같은 참여 요청 ID로 다른 내용을 보낼 수 없습니다.');return json({service:serviceMetadata(['sender.nickname']),sender:cached.sender,participant_token:cached.token,...notice(s.snapshot)},200);}
 if(s.participants.some(p=>p.client_request_id_hash===requestFingerprint))fail(409,'JOIN_RESULT_NOT_RECOVERABLE','처음 반환한 참여 secret은 복구할 수 없습니다.');if(s.participants.length>=s.snapshot.policy.participants)limited();
 const sender={id:crypto.randomUUID(),nickname},next={...s,participants:[...s.participants,{...sender,token_hash:fingerprint,client_request_id_hash:requestFingerprint}]};await this.options.repo.transaction(this.scope(),tx=>this.save(tx,next));this.state=next;this.joinResults.set(requestId,{digest,token,sender});return json({service:serviceMetadata(['sender.nickname']),sender,participant_token:token,...notice(s.snapshot)},201);
 });}
 private async send(request:Request,cap:Cap,operation:ReservationContext){const input=await this.parseBody(request,['text','client_message_id','reply_to']);const content=text(input.text,1,16384),id=text(input.client_message_id,1,128);if(new TextEncoder().encode(content).length>this.state!.snapshot.policy.textBytes)fail(413,'MESSAGE_TOO_LARGE','메시지는 최대 UTF-8 16KiB입니다.');
 const reply=input.reply_to===undefined||input.reply_to===null?null:text(input.reply_to,1,64),dedupeKey='d:'+cap.sender!.id+':'+await hash(id);
 return this.queue.run(async()=>{const s=this.live(true);this.pruneMemory();await this.cleanupPersisted();const prior=s.snapshot.persist?await this.options.repo.transaction(this.scope(),async tx=>{const index=await tx.get(C.private_messages,dedupeKey);return index?await tx.get(C.private_messages,messageKey(index.sequence as number)):undefined;}):this.ring.find(m=>m.sender.id===cap.sender!.id&&m.client_message_id===id);
 if(prior&&this.clock()-Date.parse(prior.created_at as string)<(s.snapshot.persist?s.snapshot.retention_seconds!*1000:s.snapshot.policy.memoryRetentionMs)){if(prior.text!==content||prior.reply_to!==(reply?Number(reply.split(':')[1]):null))fail(409,'IDEMPOTENCY_CONFLICT','같은 메시지 ID로 다른 내용을 보낼 수 없습니다.');const {dedupe_key:_key,...original}=prior as unknown as StoredMessage;return json({...original,service:serviceMetadata(['sender.nickname','text']),...notice(s.snapshot)});}
 let replySeq:number|null=null;if(reply!==null){const parsed=parsePrivateCursor(reply,s.epoch,s.sequence);if(parsed.status!=='ok')fail(400,'INVALID_REPLY','현재 epoch의 보관 중 메시지만 답장할 수 있습니다.');replySeq=parsed.sequence;const row=s.snapshot.persist?await this.options.repo.transaction(this.scope(),tx=>tx.get(C.private_messages,messageKey(replySeq!))):this.ring.find(m=>m.sequence===replySeq);if(!row||this.clock()-Date.parse(row.created_at as string)>=(s.snapshot.persist?s.snapshot.retention_seconds!*1000:s.snapshot.policy.memoryRetentionMs))fail(400,'INVALID_REPLY','답장할 메시지가 보관 범위에 없습니다.');}
 const now=this.clock(),own=this.acceptedAt.filter(v=>v.sender===cap.sender!.id);if(this.acceptedAt.length>=s.snapshot.policy.roomPerMinute||own.length>=s.snapshot.policy.senderPerMinute)limited(Math.max(1,(own.length>=s.snapshot.policy.senderPerMinute?own[0].at:this.acceptedAt[0].at)+60000-now));
 const message:PrivateMessage={sequence:s.sequence+1,cursor:s.epoch+':'+(s.sequence+1),sender:{id:cap.sender!.id,nickname:cap.sender!.nickname},text:content,client_message_id:id,reply_to:replySeq,created_at:new Date(now).toISOString()};
 try{privatePage([message],s.epoch,message.sequence,message.sequence,undefined,1,s.snapshot.policy,now,'open',notice(s.snapshot));}catch{fail(413,'MESSAGE_TOO_LARGE','메시지의 직렬화된 응답이 64KiB를 초과합니다.');}
 if(s.snapshot.persist){if(s.body_count>=s.snapshot.policy.persistedMessages)limited();const stored={...message,dedupe_key:dedupeKey},bytes=new TextEncoder().encode(JSON.stringify(stored)).length;await this.budget.reserve(operation,'persistent_write_bytes',bytes);this.live(true);await this.options.repo.transaction(this.scope(),async tx=>{await tx.put(C.private_messages,messageKey(message.sequence),record(stored));await tx.put(C.private_messages,dedupeKey,{sequence:message.sequence});await this.save(tx,{...s,sequence:message.sequence,body_count:s.body_count+1});});s.body_count++;}
 else {this.ring.push(message);}s.sequence=message.sequence;this.acceptedAt.push({at:now,sender:cap.sender!.id});this.pruneMemory();this.wake();return json({...message,service:serviceMetadata(['sender.nickname','text']),...notice(s.snapshot)},201);
 });}
 private async cleanupPersisted(){const s=this.state!;if(!s.snapshot.persist)return;const cutoff=this.clock()>=s.snapshot.expires_at||s.status==='deleted'?Infinity:this.clock()-s.snapshot.retention_seconds!*1000;const next=await this.options.repo.transaction(this.scope(),async tx=>{let count=0,first=s.storage_first;const rows=await tx.list(C.private_messages,{prefix:'m:',after:messageKey(first-1),limit:100});for(const row of rows){if(Date.parse(row.value.created_at as string)>cutoff)break;await tx.delete(C.private_messages,row.key);const dkey=row.value.dedupe_key as string,index=await tx.get(C.private_messages,dkey);if(index?.sequence===row.value.sequence)await tx.delete(C.private_messages,dkey);count++;first=(row.value.sequence as number)+1;}if(count)await this.save(tx,{...s,storage_first:first,body_count:s.body_count-count});return {count,first};});s.storage_first=next.first;s.body_count-=next.count;}
 async maintenance(id?:string):Promise<object>{if(id!==undefined)this.bind(id);if(!this.id)fail(400,'ROOM_ID_REQUIRED','서버가 방 식별자를 전달해야 합니다.');return this.queue.run(async()=>{await this.load();this.pruneMemory();await this.cleanupPersisted();const s=this.state!;if(this.clock()>=s.snapshot.expires_at||s.status==='deleted'){s.status='deleted';this.ring=[];this.wake();await this.options.repo.transaction(this.scope(),tx=>this.save(tx,s));}return {room_status:s.status,expires_at:s.snapshot.expires_at,next_maintenance_at:this.clock()>=s.snapshot.expires_at||s.status==='deleted'?(s.body_count?this.clock()+1000:null):s.snapshot.persist?Math.min(s.snapshot.expires_at,this.clock()+60000):s.snapshot.expires_at};});}
 private async read(request:Request,cap:Cap,after:string|undefined,limit:number,timeout:number,isWait:boolean){let acquired=false;let cleanup:(()=>void)|undefined;try{
 const start=await this.queue.run(async()=>{this.live();if(this.reading.has(cap.hash))fail(409,'WAIT_IN_PROGRESS','이 권한에는 이미 읽기 요청이 있습니다.');const ready=(this.lastRead.get(cap.hash)??-Infinity)+this.state!.snapshot.policy.readCadenceMs;if(ready>this.clock())limited(ready-this.clock());if(request.signal.aborted)fail(499,'REQUEST_ABORTED','요청이 취소되었습니다.');this.reading.add(cap.hash);acquired=true;
 try{const page=await this.page(after,limit);if(isWait&&this.state!.status==='closed'&&!page.messages.length)fail(410,'ROOM_CLOSED','방이 종료되었습니다.');if(page.messages.length||page.history_status!=='ok'||timeout===0||this.state!.status==='closed'){this.lastRead.set(cap.hash,this.clock());return {response:json(page)};}
 if(this.waiters.size>=this.state!.snapshot.policy.waits)limited();let wake!:()=>void;const pending=new Promise<void>(r=>{wake=r;});this.waiters.set(cap.hash,{wake,cursor:after});const deadline=Math.min(this.clock()+timeout,this.live().snapshot.expires_at),timer=setTimeout(wake,Math.max(0,deadline-this.clock()));request.signal.addEventListener('abort',wake,{once:true});cleanup=()=>{clearTimeout(timer);request.signal.removeEventListener('abort',wake);this.waiters.delete(cap.hash);};return {pending};}catch(e){this.reading.delete(cap.hash);acquired=false;throw e;}
 });if(start.response)return start.response;await start.pending;if(this.stopped){const response=json({error:{code:'ROOM_SHUTDOWN',message:'서버가 종료 중입니다. 다시 연결하세요.'},cursor:after??this.state!.epoch+':'+this.state!.sequence},503);response.headers.set('Retry-After','1');return response;}if(request.signal.aborted)fail(499,'REQUEST_ABORTED','요청이 취소되었습니다.');return await this.queue.run(async()=>{this.live();const page=await this.page(after,limit);if(isWait&&this.state!.status==='closed'&&!page.messages.length)fail(410,'ROOM_CLOSED','방이 종료되었습니다.');this.lastRead.set(cap.hash,this.clock());return json(page);});
 }finally{cleanup?.();if(acquired)this.reading.delete(cap.hash);}}
 private async parseBody(request:Request,allowed:string[]){const limit=this.state!.snapshot.policy.bodyInflight;if(this.stopped)fail(503,'ROOM_SHUTDOWN','서버가 종료 중입니다.');if(this.bodies>=limit)limited();this.bodies++;const controller=new AbortController(),abort=()=>controller.abort();this.bodyControllers.add(controller);request.signal.addEventListener('abort',abort,{once:true});if(request.signal.aborted)abort();try{return await publicBody(new Request(request,{signal:controller.signal}),{jsonBytes:this.state!.snapshot.policy.jsonBytes,bodyMs:5000},allowed);}finally{request.signal.removeEventListener('abort',abort);this.bodyControllers.delete(controller);this.bodies--;}}
 async fetch(request:Request):Promise<Response>{try{const limit=this.state?.snapshot.policy.handlers??64;if(this.handlers>=limit)return publicError(new PublicError(429,'RATE_LIMITED','방 요청 한도를 초과했습니다.',1000));this.handlers++;try{return await this.dispatch(request);}finally{this.handlers--;}}finally{cancelUnusedRequestBody(request);}}
 private async dispatch(request:Request):Promise<Response>{try{const url=new URL(request.url),route=/^\/api\/v1\/rooms\/([a-zA-Z0-9_-]+)(?:\/(participants|messages|wait|close))?$/.exec(url.pathname),entry=/^\/r\/([a-zA-Z0-9_-]+)\/([\w-]{43})$/.exec(url.pathname);if(!route&&!entry)fail(404,'NOT_FOUND','경로가 없습니다.');this.bind((route??entry)![1]);const token=entry?entry[2]:bearer(request),fingerprint=await hash(token);const path=route?.[2]??'',cleanup=!!route&&((request.method==='DELETE'&&path==='')||(request.method==='POST'&&path==='close'));const valid=!!entry&&request.method==='GET'||!!route&&((path===''&&['GET','DELETE'].includes(request.method))||(path==='participants'&&request.method==='POST')||(path==='messages'&&['GET','POST'].includes(request.method))||(path==='wait'&&request.method==='GET')||(path==='close'&&request.method==='POST'));if(!valid)fail(404,'NOT_FOUND','경로가 없습니다.');const operation=cleanup?undefined:await this.budget.admit();await this.queue.run(()=>this.load());const cap=this.capability(fingerprint);
 let response:Response;if(entry){if(request.method!=='GET'||!['invite','read'].includes(cap.role))fail(403,'CAPABILITY_DENIED','공유 링크 권한이 없습니다.');response=new Response(this.guide(),{headers:{'Content-Type':'text/markdown; charset=utf-8'}});}
 else if(path===''&&request.method==='GET')response=json({service:serviceMetadata(['room.purpose']),room:roomView(this.live()),permissions:{read:true,join:cap.role==='invite'&&this.state!.status==='open',write:cap.role==='participant'&&this.state!.status==='open',manage:cap.role==='owner'}});
 else if(path==='participants'&&request.method==='POST'){this.require(cap,'invite');response=await this.join(request);}
 else if(path==='messages'&&request.method==='POST'){this.require(cap,'participant');response=await this.send(request,cap,operation!);}
 else if((path==='messages'||path==='wait')&&request.method==='GET')response=await this.read(request,cap,url.searchParams.get('after')??undefined,queryInt(url,'limit',this.state!.snapshot.policy.pageSize,1,this.state!.snapshot.policy.pageSize),path==='wait'?queryInt(url,'timeout',25,0,Math.floor(this.state!.snapshot.policy.waitMs/1000))*1000:0,path==='wait');
 else if((path==='close'&&request.method==='POST')||(path===''&&request.method==='DELETE')){this.require(cap,'owner');response=await this.queue.run(async()=>{const s=this.live();s.status=request.method==='DELETE'?'deleted':'closed';if(s.status==='deleted')this.ring=[];await this.options.repo.transaction(this.scope(),tx=>this.save(tx,s));if(s.status==='deleted')await this.cleanupPersisted();this.wake();return s.status==='deleted'?new Response(null,{status:204}):json({service:serviceMetadata(['room.purpose']),room:roomView(s)});});}
 else fail(404,'NOT_FOUND','경로가 없습니다.');return operation?await this.budget.respond(response,operation):response;
 }catch(error){return error instanceof NoticeChanged?json({error:{code:error.code,message:'현재 보관 조건을 확인하세요.'},notice:error.notice},409):publicError(error);}}
 private guide():string{const s=this.live().snapshot;return '# 톡톡 비공개방\n\n'+AGENT_SAFETY_NOTICE+'\n\n서비스 고지:\n\n'+untrustedMarkdown({...notice(s),created_at:s.created_at,expires_at:s.expires_at,policy:s.policy})+'\n\n비신뢰 방 데이터:\n\n'+untrustedMarkdown({purpose:s.purpose})+'\n\n초기 읽기는 최근 '+s.policy.firstWindowMs/1000+'초/'+s.policy.firstWindowMessages+'개입니다. 이후 마지막 반영한 epoch:sequence cursor로 delta를 읽고 history_gap/history_reset을 표시하세요. 같은 sender/client_message_id 중복 제거는 현재 보관 범위까지만 보장합니다. 참가 POST에는 nickname, client_request_id, notice_version, visibility:private, retention_mode:'+ (s.persist?'persisted':'memory')+'가 필요합니다. 안내 확인은 machine acknowledgement이며 사람 동의를 대신하지 않습니다. owner secret은 공유하지 마세요.\n';}
 async inspect(id?:string):Promise<object>{if(id!==undefined)this.bind(id);if(!this.id)fail(400,'ROOM_ID_REQUIRED','서버가 방 식별자를 전달해야 합니다.');return this.queue.run(async()=>{await this.load();const s=this.state!;return {id:s.snapshot.id,status:this.clock()>=s.snapshot.expires_at?'expired':s.status,expires_at:s.snapshot.expires_at,persist:s.snapshot.persist,initialized:true};});}
 shutdown():void{this.stopped=true;for(const controller of this.bodyControllers)controller.abort();this.wake();}
 diagnostics(){return {epoch:this.state?.epoch,sequence:this.state?.sequence??0,active_handlers:this.handlers,body_inflight:this.bodies,active_waits:this.waiters.size,active_reads:this.reading.size,memory_messages:this.ring.length,...this.budget.diagnostics()};}
}
