import {hash,fail} from './http';
import {PRIVATE_NOTICE,LEGACY_PRIVATE_NOTICE,MAX_PRIVATE_PURPOSE_CHARACTERS,validatePrivatePolicy,type PrivateRoomInit,type PrivateParticipant} from './private-contracts';
export interface PrivateState {snapshot:PrivateRoomInit;init_digest:string;status:'open'|'closed'|'deleted';epoch:string;sequence:number;storage_first:number;body_count:number;participants:PrivateParticipant[];}
function canonical(value:unknown):string {if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';}
export async function initSnapshot(input:PrivateRoomInit):Promise<{snapshot:PrivateRoomInit;digest:string}>{
 const keys=['id','creator_id','created_at','expires_at','purpose','invite_hash','read_hash','owner_hash','settings_revision','mode','visibility','persist','retention_seconds','notice_version','creator_ack','policy'];if(!input||Object.keys(input).some(k=>!keys.includes(k)))fail(400,'INVALID_SNAPSHOT','미허용 생성 snapshot 필드입니다.');
 if(!input||!/^[a-zA-Z0-9_-]{1,128}$/.test(input.id)||typeof input.creator_id!=='string'||input.creator_id.length<1||input.creator_id.length>128||!Number.isSafeInteger(input.created_at)||!Number.isSafeInteger(input.expires_at)||input.expires_at<=input.created_at||typeof input.purpose!=='string'||Array.from(input.purpose).length>MAX_PRIVATE_PURPOSE_CHARACTERS||!Number.isSafeInteger(input.settings_revision)||input.settings_revision<1||!['DEMO','HOSTED'].includes(input.mode)||input.visibility!=='private'||typeof input.persist!=='boolean'||![PRIVATE_NOTICE,LEGACY_PRIVATE_NOTICE].includes(input.notice_version))fail(400,'INVALID_SNAPSHOT','방 생성 snapshot이 올바르지 않습니다.');
 for(const h of [input.invite_hash,input.read_hash,input.owner_hash])if(!/^[a-f0-9]{64}$/.test(h))fail(400,'INVALID_SNAPSHOT','권한 지문이 올바르지 않습니다.');if(new Set([input.invite_hash,input.read_hash,input.owner_hash]).size!==3)fail(400,'INVALID_SNAPSHOT','권한은 서로 분리되어야 합니다.');
 const ack=input.creator_ack;if(!ack||Object.keys(ack).some(k=>!['kind','version','confirmed_at','owner_account_id'].includes(k))||!['anonymous_declaration','account_confirmation','agent_owner_confirmation'].includes(ack.kind)||ack.version!==input.notice_version||!Number.isSafeInteger(ack.confirmed_at)||ack.confirmed_at>input.created_at||ack.confirmed_at<0||(ack.kind==='anonymous_declaration'?ack.owner_account_id!==null:typeof ack.owner_account_id!=='string'||!/^[a-f0-9-]{36}$/.test(ack.owner_account_id)))fail(400,'INVALID_SNAPSHOT','생성 안내 확인 snapshot이 올바르지 않습니다.');
 if(input.persist&&(ack.kind==='anonymous_declaration'||!Number.isSafeInteger(input.retention_seconds)||input.retention_seconds!<1))fail(403,'PERSIST_DENIED','익명 방은 장기 보관을 선택할 수 없습니다.');if(!input.persist&&input.retention_seconds!==null)fail(400,'INVALID_SNAPSHOT','최근 버퍼에는 별도 장기 보관 기간을 지정하지 않습니다.');
 const policy=validatePrivatePolicy(input.policy),snapshot=JSON.parse(JSON.stringify({...input,creator_ack:{...ack},policy})) as PrivateRoomInit;return {snapshot,digest:await hash(canonical(snapshot))};
}
export function usesRecentBuffer(snapshot:PrivateRoomInit){return !snapshot.persist&&snapshot.notice_version===PRIVATE_NOTICE;}
export function notice(snapshot:PrivateRoomInit){const recent=usesRecentBuffer(snapshot);return {notice_version:snapshot.notice_version,visibility:'private',retention_mode:snapshot.persist?'persisted':recent?'recent_buffer':'memory',retention_seconds:recent?Math.min(snapshot.policy.memoryRetentionMs/1000,(snapshot.expires_at-snapshot.created_at)/1000):snapshot.retention_seconds,...(recent?{recent_buffer:{max_messages:Math.min(500,snapshot.policy.memoryMessages),max_bytes:2097152}}:{}),metadata_persisted:true,link_possession_access:true,end_to_end_encrypted:false};}
export function roomView(state:PrivateState){const s=state.snapshot;return {id:s.id,purpose:s.purpose,status:state.status,created_at:new Date(s.created_at).toISOString(),expires_at:new Date(s.expires_at).toISOString(),settings_revision:s.settings_revision,mode:s.mode,history_retention_seconds:s.persist?s.retention_seconds:s.policy.memoryRetentionMs/1000,...notice(s)};}
export const messageKey=(sequence:number)=>'m:'+String(sequence).padStart(16,'0');
